Repository arduino/arduino-ide, pull requests merged in 2021-12, with the labels that each got.

#664 Remove gRPC error code from error notifications
  arduino-ide-extension/src/browser/contributions/burn-bootloader.ts
  arduino-ide-extension/src/browser/contributions/upload-sketch.ts
  arduino-ide-extension/src/browser/contributions/verify-sketch.ts
  arduino-ide-extension/src/node/core-service-impl.ts
  i18n/en.json
Labels: type: enhancement, topic: code

#687 Update `README.md` with translations project link
  README.md
Labels: topic: documentation

#708 Use major version ref of `carlosperate/download-file-action`
  .github/workflows/sync-labels.yml
Labels: type: enhancement, topic: infrastructure
