Repository arduino/arduino-ide, pull requests merged in 2021-11, with the labels that each got.

#564 Remove gRPC errors codes from compile/upload console output
  arduino-ide-extension/src/node/core-service-impl.ts
Labels: type: enhancement

#579 Open Save as... dialog when saving sketches for the first time
  arduino-ide-extension/src/browser/contributions/save-sketch.ts
  arduino-ide-extension/src/node/sketches-service-impl.ts
Labels: topic: code, type: imperfection

#616 Fix i18n:generate command not including tsx files
  i18n/en.json
  package.json
Labels: topic: infrastructure, type: imperfection

#611 Disable Breadcrumbs
  browser-app/package.json
  electron-app/package.json
Labels: topic: code

#612 Fix tabs ordering
  arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx
  arduino-ide-extension/src/browser/theia/core/shell-layout-restorer.ts
Labels: topic: code, type: imperfection

#597 Serial Plotter implementation
  arduino-ide-extension/README.md
  arduino-ide-extension/package.json
  arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/boards/boards-service-provider.ts
  arduino-ide-extension/src/browser/contributions/board-selection.ts
  arduino-ide-extension/src/browser/contributions/burn-bootloader.ts
  arduino-ide-extension/src/browser/contributions/upload-sketch.ts
  arduino-ide-extension/src/browser/menu/arduino-menus.ts
  arduino-ide-extension/src/browser/monitor/monitor-connection.ts
  arduino-ide-extension/src/browser/monitor/monitor-service-client-impl.ts
  arduino-ide-extension/src/browser/serial/monitor/monitor-utils.ts
  arduino-ide-extension/src/browser/serial/monitor/monitor-view-contribution.tsx
  arduino-ide-extension/src/browser/serial/monitor/monitor-widget.tsx
  arduino-ide-extension/src/browser/serial/monitor/serial-monitor-send-input.tsx
  arduino-ide-extension/src/browser/serial/monitor/serial-monitor-send-output.tsx
  arduino-ide-extension/src/browser/serial/plotter/plotter-frontend-contribution.ts
  arduino-ide-extension/src/browser/serial/plotter/protocol.ts
  arduino-ide-extension/src/browser/serial/serial-connection-manager.ts
  arduino-ide-extension/src/browser/serial/serial-model.ts
  arduino-ide-extension/src/browser/serial/serial-service-client-impl.ts
  arduino-ide-extension/src/common/protocol/core-service.ts
  arduino-ide-extension/src/common/protocol/index.ts
  arduino-ide-extension/src/common/protocol/monitor-service.ts
  arduino-ide-extension/src/common/protocol/serial-service.ts
  arduino-ide-extension/src/electron-main/theia/electron-main-application.ts
  arduino-ide-extension/src/node/arduino-ide-backend-module.ts
  arduino-ide-extension/src/node/core-service-impl.ts
  arduino-ide-extension/src/node/plotter/plotter-backend-contribution.ts
  arduino-ide-extension/src/node/serial/monitor-client-provider.ts
  arduino-ide-extension/src/node/serial/serial-service-impl.ts
  arduino-ide-extension/src/node/web-socket/web-socket-service-impl.ts
  arduino-ide-extension/src/node/web-socket/web-socket-service.ts
  arduino-ide-extension/src/test/browser/boards-auto-installer.test.ts
  arduino-ide-extension/src/test/browser/fixtures/boards.ts
  arduino-ide-extension/src/test/browser/fixtures/serial.ts
  arduino-ide-extension/src/test/browser/monitor-utils.test.ts
  arduino-ide-extension/src/test/browser/serial-connection-manager.test.ts
  i18n/en.json
  yarn.lock
Labels: topic: code

#614 Rework listing of discovered ports
  arduino-ide-extension/package.json
  arduino-ide-extension/src/browser/boards/boards-config.tsx
  arduino-ide-extension/src/browser/boards/boards-service-provider.ts
  arduino-ide-extension/src/browser/boards/boards-toolbar-item.tsx
  arduino-ide-extension/src/browser/contributions/board-selection.ts
  arduino-ide-extension/src/browser/style/boards-config-dialog.css
  arduino-ide-extension/src/common/protocol/boards-service.ts
  arduino-ide-extension/src/node/board-discovery.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/board_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/board_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_grpc_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_grpc_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/core_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/core_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/monitor_grpc_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/monitor_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/monitor_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/port_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/port_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/upload_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/upload_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/debug/v1/debug_grpc_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/debug/v1/debug_grpc_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/debug/v1/debug_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/debug/v1/debug_pb.js
  arduino-ide-extension/src/node/cli-protocol/google/rpc/status_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/google/rpc/status_pb.js
  i18n/en.json
Labels: type: enhancement, topic: code

#550 Add dialog to insert user fields for board that require them to upload
  arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/boards/boards-service-provider.ts
  arduino-ide-extension/src/browser/contributions/upload-sketch.ts
  arduino-ide-extension/src/browser/contributions/verify-sketch.ts
  arduino-ide-extension/src/browser/dialogs/user-fields/user-fields-component.tsx
  arduino-ide-extension/src/browser/dialogs/user-fields/user-fields-dialog.tsx
  arduino-ide-extension/src/browser/style/index.css
  arduino-ide-extension/src/browser/style/user-fields-dialog.css
  arduino-ide-extension/src/common/protocol/boards-service.ts
  arduino-ide-extension/src/common/protocol/core-service.ts
  arduino-ide-extension/src/node/boards-service-impl.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_grpc_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_grpc_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_pb.js
  arduino-ide-extension/src/node/core-service-impl.ts
  i18n/en.json
  yarn.lock
Labels: type: enhancement, topic: code

#635 Remove language server log preference
  arduino-ide-extension/src/browser/settings.tsx
Labels: type: enhancement, topic: code
