Repository arduino/arduino-ide, pull requests merged in 2022-11, with the labels that each got.

#1577 feat: build IDE2 on darwin arm64
  .github/workflows/arduino-stats.yml
  .github/workflows/build.yml
  .github/workflows/check-i18n-task.yml
  .github/workflows/compose-full-changelog.yml
  .github/workflows/github-stats.yml
  .github/workflows/i18n-nightly-push.yml
  .github/workflows/i18n-weekly-pull.yml
  .github/workflows/themes-weekly-pull.yml
  arduino-ide-extension/package.json
  arduino-ide-extension/scripts/download-cli.js
  arduino-ide-extension/scripts/download-ls.js
  docs/development.md
  docs/internal/Arm.md
  docs/internal/Ubuntu.md
  electron/build/template-package.json
  electron/packager/conf-node-gyp.sh
  electron/packager/config.js
  electron/packager/index.js
  electron/packager/package.json
  package.json
  yarn.lock
Labels: type: enhancement, topic: infrastructure, architecture: arm, os: macos

#1605 Configure Dependabot to check for outdated actions used in workflows
  .github/dependabot.yml
Labels: type: enhancement, topic: infrastructure

#1604 Migrate workflows from deprecated `set-output` commands
  .github/workflows/build.yml
  .github/workflows/check-certificates.yml
  .github/workflows/compose-full-changelog.yml
  .github/workflows/sync-labels.yml
Labels: topic: infrastructure, type: imperfection

#1623 fix: do not trim stdout of `clang-format` process
  arduino-ide-extension/src/node/exec-util.ts
Labels: topic: code, type: imperfection

#1616 fix: Handle gracefully when trying to detect invalid sketch name error and folder is missing on filesystem
  arduino-ide-extension/src/electron-main/theia/electron-main-application.ts
  arduino-ide-extension/src/node/arduino-daemon-impl.ts
  arduino-ide-extension/src/node/config-service-impl.ts
  arduino-ide-extension/src/node/sketches-service-impl.ts
  arduino-ide-extension/src/node/utils/errors.ts
  scripts/i18n/transifex-pull.js
Labels: topic: code, type: imperfection

#1581 #1580 Create remote sketch
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/contributions/close.ts
  arduino-ide-extension/src/browser/contributions/new-cloud-sketch.ts
  arduino-ide-extension/src/browser/contributions/new-sketch.ts
  arduino-ide-extension/src/browser/contributions/open-sketch.ts
  arduino-ide-extension/src/browser/contributions/save-sketch.ts
  arduino-ide-extension/src/browser/create/create-uri.ts
  arduino-ide-extension/src/browser/local-cache/local-cache-fs-provider.ts
  arduino-ide-extension/src/browser/style/dialogs.css
  arduino-ide-extension/src/browser/style/sketchbook.css
  arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-composite-widget.tsx
  arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-tree-model.ts
  arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-tree-widget.tsx
  arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-tree.ts
  arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-widget.ts
  arduino-ide-extension/src/browser/widgets/sketchbook/create-new.tsx
  arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-composite-widget.tsx
  arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-tree-widget.tsx
  arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-widget.tsx
  arduino-ide-extension/src/electron-browser/theia/core/electron-main-menu-factory.ts
  i18n/en.json
Labels: type: enhancement, topic: code

#1617 fix: avoid ENOTDIR when opening second instance.
  arduino-ide-extension/src/electron-main/theia/electron-main-application.ts
Labels: topic: code, type: imperfection

#1621 fix: relaxed condition to check if resource exists
  arduino-ide-extension/src/node/sketches-service-impl.ts
Labels: topic: code, os: linux, type: imperfection

#1622 fix: escaped regex chars in pattern
  arduino-ide-extension/package.json
  arduino-ide-extension/src/electron-main/theia/electron-main-application.ts
  arduino-ide-extension/src/node/sketches-service-impl.ts
  yarn.lock
Labels: topic: code, type: imperfection

#1649 fix: flawed timing issue when opening editors
  arduino-ide-extension/src/browser/contributions/open-sketch-files.ts
  arduino-ide-extension/src/electron-main/theia/electron-main-application.ts
  arduino-ide-extension/src/node/sketches-service-impl.ts
Labels: topic: code, type: imperfection

#1673 feat: progress for the remote sketch creation
  arduino-ide-extension/src/browser/contributions/new-cloud-sketch.ts
  arduino-ide-extension/src/browser/style/dialogs.css
  i18n/en.json
Labels: type: enhancement, topic: code

#1684 Fix nightly build links in issue forms
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: topic: infrastructure, type: imperfection

#1683 Use 0.29.0 CLI in IDE2
  arduino-ide-extension/package.json
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_grpc_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_grpc_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/lib_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/lib_pb.js
  arduino-ide-extension/src/node/core-client-provider.ts
  arduino-ide-extension/src/node/grpc-progressible.ts
Labels: topic: infrastructure, type: imperfection, topic: CLI

#1687 Bump version metadata post release: 2.0.3
  arduino-ide-extension/package.json
  electron-app/package.json
  package.json
Labels: type: enhancement, topic: infrastructure

#1719 fix: editor widget resolving when creating new tab
  arduino-ide-extension/src/browser/contributions/open-sketch-files.ts
Labels: topic: code, type: imperfection

#1686 Fix keybindings to switch between tabs on MacOs
  arduino-ide-extension/src/browser/theia/core/common-frontend-contribution.ts
Labels: topic: code, os: macos, type: imperfection

#1676 fix: main sketch file editor focus on layout reset
  arduino-ide-extension/src/browser/contributions/open-sketch-files.ts
  arduino-ide-extension/src/browser/theia/core/frontend-application.ts
Labels: topic: code, type: imperfection

#1717 fix: remote sketch creation if tree is not active
  arduino-ide-extension/src/browser/contributions/new-cloud-sketch.ts
  arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-widget.tsx
Labels: topic: code, type: imperfection

#1703 fix: update monitor settings only if it's changed
  arduino-ide-extension/package.json
  arduino-ide-extension/src/node/monitor-service.ts
  yarn.lock
Labels: topic: code, type: imperfection, topic: serial monitor
