Repository arduino/arduino-ide, pull requests merged in 2022-07, with the labels that each got.

#1128 Remove tabs context menu
  arduino-ide-extension/src/browser/theia/core/tab-bars.ts
Labels: topic: code

#1131 #979 fix platform installation prompt only made for boards listed in oldest release
  arduino-ide-extension/src/node/boards-service-impl.ts
Labels: topic: code, type: imperfection

#1140 remove border from tree indent
  electron-app/package.json
Labels: type: enhancement, topic: code

#1148 Increase sketchbook tree indentation to reflect design system
  arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-tree-widget.tsx
Labels: type: enhancement, topic: code, type: imperfection

#1146 Increase sketchbook list item height
  arduino-ide-extension/src/browser/style/index.css
  arduino-ide-extension/src/browser/style/sketchbook.css
Labels: topic: code, type: imperfection

#1123 change output buffer to setTimeout instead of setInterval
  arduino-ide-extension/src/node/core-service-impl.ts
  arduino-ide-extension/src/node/utils/buffers.ts
Labels: topic: code, type: imperfection

#1130 #854 fix platform installation only offered if port is selected
  arduino-ide-extension/src/browser/boards/boards-auto-installer.ts
  arduino-ide-extension/src/browser/boards/boards-service-provider.ts
Labels: topic: code, type: imperfection

#1151 Window min size
  arduino-ide-extension/src/browser/dialogs/settings/settings-component.tsx
  arduino-ide-extension/src/browser/dialogs/settings/settings-dialog.tsx
  arduino-ide-extension/src/browser/style/dialogs.css
  arduino-ide-extension/src/browser/style/settings-dialog.css
  arduino-ide-extension/src/electron-main/theia/electron-main-application.ts
Labels: topic: code

#1122 Update buttons style
  arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx
  arduino-ide-extension/src/browser/data/arduino.color-theme.json
  arduino-ide-extension/src/browser/data/dark.color-theme.json
  arduino-ide-extension/src/browser/data/default.color-theme.json
  arduino-ide-extension/src/browser/dialogs/certificate-uploader/certificate-uploader-component.tsx
  arduino-ide-extension/src/browser/style/dialogs.css
  arduino-ide-extension/src/browser/style/fonts.css
  arduino-ide-extension/src/browser/style/fonts/OpenSans-Bold-webfont.woff
  arduino-ide-extension/src/browser/style/fonts/OpenSans-Regular-webfont.woff
  arduino-ide-extension/src/browser/style/index.css
  arduino-ide-extension/src/browser/style/list-widget.css
  arduino-ide-extension/src/browser/style/main.css
  arduino-ide-extension/src/browser/style/sketchbook.css
  arduino-ide-extension/src/browser/theia/messages/notification-component.tsx
  arduino-ide-extension/src/browser/widgets/component-list/list-item-renderer.tsx
Labels: type: enhancement, status: blocked, topic: code

#1162 #1161: Fixed missing core client in the monitor service.
  arduino-ide-extension/src/node/arduino-ide-backend-module.ts
  arduino-ide-extension/src/node/core-client-provider.ts
  arduino-ide-extension/src/node/monitor-manager.ts
  arduino-ide-extension/src/node/monitor-service-factory.ts
  arduino-ide-extension/src/node/monitor-service.ts
Labels: topic: code, type: imperfection, topic: serial monitor

#1165 Let DI framework create `MonitorService` instances
  arduino-ide-extension/src/node/arduino-ide-backend-module.ts
  arduino-ide-extension/src/node/core-client-provider.ts
  arduino-ide-extension/src/node/monitor-manager.ts
  arduino-ide-extension/src/node/monitor-service-factory.ts
  arduino-ide-extension/src/node/monitor-service.ts
Labels: type: enhancement, topic: code

#1174 Avoid twice serial plotter apps
  arduino-ide-extension/package.json
  arduino-ide-extension/src/node/plotter/plotter-backend-contribution.ts
Labels: topic: infrastructure, type: imperfection

#1172 Fix settings dialog size
  arduino-ide-extension/src/browser/dialogs/settings/settings-dialog.tsx
  arduino-ide-extension/src/browser/style/settings-dialog.css
Labels: topic: code, type: imperfection

#1190 Update the background of a selected item in the sketchbook
  arduino-ide-extension/src/browser/style/sketchbook.css
Labels: topic: code

#1166 Add language packs
  arduino-ide-extension/src/node/arduino-localization-contribution.ts
  electron/build/template-package.json
  package.json
Labels: type: enhancement, topic: infrastructure

#1169 Prevent overwriting existing libraries and platforms at first IDE start-up
  arduino-ide-extension/package.json
  arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/contributions/first-startup-installer.ts
  arduino-ide-extension/src/common/protocol/installable.ts
  arduino-ide-extension/src/common/protocol/library-service.ts
  arduino-ide-extension/src/node/boards-service-impl.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/compile_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/compile_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/core_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/core_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/lib_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/lib_pb.js
  arduino-ide-extension/src/node/library-service-impl.ts
Labels: topic: code, type: imperfection

#1193 New Board Selector UI: show port protocol
  arduino-ide-extension/arduino-icons.json
  arduino-ide-extension/package.json
  arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx
  arduino-ide-extension/src/browser/boards/boards-service-provider.ts
  arduino-ide-extension/src/browser/boards/boards-toolbar-item.tsx
  arduino-ide-extension/src/browser/data/dark.color-theme.json
  arduino-ide-extension/src/browser/data/default.color-theme.json
  arduino-ide-extension/src/browser/style/boards-config-dialog.css
  arduino-ide-extension/src/browser/style/fonts.css
  arduino-ide-extension/src/browser/style/fonts/FontAwesome.svg
  arduino-ide-extension/src/browser/style/fonts/FontAwesome.ttf
  arduino-ide-extension/src/browser/style/fonts/FontAwesome.woff
  arduino-ide-extension/src/browser/style/main.css
  arduino-ide-extension/src/common/protocol/boards-service.ts
  i18n/en.json
  yarn.lock
Labels: topic: code

#1160 IDE startup theme based on OS theme
  electron/.gitignore
  electron/build/patch/backend/main.js
  electron/build/patch/frontend/index.js
  electron/build/template-package.json
  electron/build/webpack.config.js
  electron/packager/index.js
Labels: topic: code, type: imperfection, topic: theme

#1152 #1089: IDE2 falls back to new sketch if opening failed.
  arduino-ide-extension/src/browser/arduino-commands.ts
  arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/arduino-preferences.ts
  arduino-ide-extension/src/browser/boards/boards-service-provider.ts
  arduino-ide-extension/src/browser/boards/boards-toolbar-item.tsx
  arduino-ide-extension/src/browser/contributions/check-for-updates.ts
  arduino-ide-extension/src/browser/contributions/compiler-errors.ts
  arduino-ide-extension/src/browser/contributions/contribution.ts
  arduino-ide-extension/src/browser/contributions/debug.ts
  arduino-ide-extension/src/browser/contributions/edit-contributions.ts
  arduino-ide-extension/src/browser/contributions/ino-language.ts
  arduino-ide-extension/src/browser/contributions/open-boards-config.ts
  arduino-ide-extension/src/browser/contributions/open-sketch-files.ts
  arduino-ide-extension/src/browser/contributions/selected-board.ts
  arduino-ide-extension/src/browser/contributions/sketch-files-tracker.ts
  arduino-ide-extension/src/browser/contributions/sketchbook.ts
  arduino-ide-extension/src/browser/contributions/upload-sketch.ts
  arduino-ide-extension/src/browser/contributions/verify-sketch.ts
  arduino-ide-extension/src/browser/create/create-api.ts
  arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx
  arduino-ide-extension/src/browser/editor-mode.ts
  arduino-ide-extension/src/browser/style/index.css
  arduino-ide-extension/src/browser/theia/core/frontend-application.ts
  arduino-ide-extension/src/browser/theia/workspace/workspace-service.ts
  arduino-ide-extension/src/browser/theia/workspace/workspace-variable-contribution.ts
  arduino-ide-extension/src/browser/utils/window.ts
  arduino-ide-extension/src/browser/widgets/sketchbook/startup-task.ts
  arduino-ide-extension/src/common/protocol/ide-updater.ts
  arduino-ide-extension/src/common/protocol/sketches-service-client-impl.ts
  arduino-ide-extension/src/common/protocol/sketches-service.ts
  arduino-ide-extension/src/node/sketches-service-impl.ts
  electron/build/scripts/patch-theia-preload.js
  electron/build/template-package.json
  i18n/en.json
Labels: topic: code, type: imperfection

#1194 Toolbar enhancements
  arduino-ide-extension/arduino-icons.json
  arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx
  arduino-ide-extension/src/browser/boards/boards-list-widget.ts
  arduino-ide-extension/src/browser/contributions/debug.ts
  arduino-ide-extension/src/browser/contributions/new-sketch.ts
  arduino-ide-extension/src/browser/contributions/open-sketch.ts
  arduino-ide-extension/src/browser/contributions/save-sketch.ts
  arduino-ide-extension/src/browser/contributions/sketch-control.ts
  arduino-ide-extension/src/browser/data/dark.color-theme.json
  arduino-ide-extension/src/browser/data/default.color-theme.json
  arduino-ide-extension/src/browser/icons/boards-manager.svg
  arduino-ide-extension/src/browser/icons/monitor.svg
  arduino-ide-extension/src/browser/icons/plotter.svg
  arduino-ide-extension/src/browser/icons/sketch-tabs-menu.svg
  arduino-ide-extension/src/browser/icons/upload.svg
  arduino-ide-extension/src/browser/icons/verify.svg
  arduino-ide-extension/src/browser/serial/plotter/plotter-frontend-contribution.ts
  arduino-ide-extension/src/browser/style/boards-config-dialog.css
  arduino-ide-extension/src/browser/style/fonts.css
  arduino-ide-extension/src/browser/style/fonts/FontAwesome.svg
  arduino-ide-extension/src/browser/style/fonts/FontAwesome.ttf
  arduino-ide-extension/src/browser/style/fonts/FontAwesome.woff
  arduino-ide-extension/src/browser/style/main.css
Labels: type: enhancement, topic: code

#1213 Dropped `compile.optimizeForDebug` preference.
  arduino-ide-extension/src/browser/arduino-preferences.ts
  arduino-ide-extension/src/browser/contributions/debug.ts
  arduino-ide-extension/src/browser/contributions/upload-sketch.ts
  arduino-ide-extension/src/browser/contributions/verify-sketch.ts
  i18n/en.json
Labels: topic: code, type: imperfection

#1215 Toolbar debug button
  arduino-ide-extension/src/browser/contributions/debug.ts
  arduino-ide-extension/src/browser/style/main.css
Labels: topic: code, type: imperfection

#1209 Add typing support to steppers
  arduino-ide-extension/src/browser/dialogs/settings/settings-component.tsx
  arduino-ide-extension/src/browser/dialogs/settings/settings-step-input.tsx
  arduino-ide-extension/src/browser/style/index.css
  arduino-ide-extension/src/browser/style/settings-step-input.css
Labels: type: enhancement, topic: code

#1214 Fix board selector synchronization
  arduino-ide-extension/src/browser/boards/boards-service-provider.ts
  arduino-ide-extension/src/browser/boards/boards-toolbar-item.tsx
  arduino-ide-extension/src/browser/contributions/open-boards-config.ts
Labels: topic: code, type: imperfection

#1237 #374: ensure compile verbose pref is included on upload
  arduino-ide-extension/src/browser/contributions/upload-sketch.ts
  arduino-ide-extension/src/common/protocol/core-service.ts
  arduino-ide-extension/src/node/core-service-impl.ts
Labels: topic: code, type: imperfection

#1238 #1223: use theme service on settings load
  arduino-ide-extension/src/browser/dialogs/settings/settings.ts
  electron/build/patch/frontend/index.js
Labels: topic: code, type: imperfection

#1264 remove state from stepper input and simplify
  arduino-ide-extension/src/browser/dialogs/settings/settings-step-input.tsx
Labels: topic: code, type: imperfection
