Repository arduino/arduino-ide, pull requests merged in 2022-06, with the labels that each got.

#893 Save dialog for closing temporary sketch and unsaved files
  arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx
  arduino-ide-extension/src/browser/contributions/close.ts
  arduino-ide-extension/src/electron-browser/theia/core/electron-menu-module.ts
  arduino-ide-extension/src/electron-main/arduino-electron-main-module.ts
  arduino-ide-extension/src/electron-main/theia/theia-electron-window.ts
  i18n/en.json
  package.json
Labels: topic: code, type: imperfection

#991 dark theme implementation for IDE 2
  .github/workflows/themes-weekly-pull.yml
  .gitignore
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/data/dark.color-theme.json
  arduino-ide-extension/src/browser/data/default.color-theme.json
  package.json
  scripts/themes/theme-generator.js
  scripts/themes/theme-tokens-pull.js
  yarn.lock
Labels: type: enhancement

#982 Pluggable monitor
  arduino-ide-extension/package.json
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/contributions/burn-bootloader.ts
  arduino-ide-extension/src/browser/contributions/upload-sketch.ts
  arduino-ide-extension/src/browser/contributions/verify-sketch.ts
  arduino-ide-extension/src/browser/dialogs/firmware-uploader/firmware-uploader-component.tsx
  arduino-ide-extension/src/browser/dialogs/firmware-uploader/firmware-uploader-dialog.tsx
  arduino-ide-extension/src/browser/monitor-manager-proxy-client-impl.ts
  arduino-ide-extension/src/browser/monitor-model.ts
  arduino-ide-extension/src/browser/serial/monitor/monitor-view-contribution.tsx
  arduino-ide-extension/src/browser/serial/monitor/monitor-widget.tsx
  arduino-ide-extension/src/browser/serial/monitor/serial-monitor-send-input.tsx
  arduino-ide-extension/src/browser/serial/monitor/serial-monitor-send-output.tsx
  arduino-ide-extension/src/browser/serial/plotter/plotter-frontend-contribution.ts
  arduino-ide-extension/src/browser/serial/plotter/protocol.ts
  arduino-ide-extension/src/browser/serial/serial-connection-manager.ts
  arduino-ide-extension/src/browser/serial/serial-model.ts
  arduino-ide-extension/src/browser/serial/serial-service-client-impl.ts
  arduino-ide-extension/src/common/protocol/arduino-firmware-uploader.ts
  arduino-ide-extension/src/common/protocol/core-service.ts
  arduino-ide-extension/src/common/protocol/index.ts
  arduino-ide-extension/src/common/protocol/monitor-service.ts
  arduino-ide-extension/src/common/protocol/serial-service.ts
  arduino-ide-extension/src/common/utils.ts
  arduino-ide-extension/src/node/arduino-firmware-uploader-impl.ts
  arduino-ide-extension/src/node/arduino-ide-backend-module.ts
  arduino-ide-extension/src/node/core-service-impl.ts
  arduino-ide-extension/src/node/monitor-manager-proxy-impl.ts
  arduino-ide-extension/src/node/monitor-manager.ts
  arduino-ide-extension/src/node/monitor-service-factory.ts
  arduino-ide-extension/src/node/monitor-service.ts
  arduino-ide-extension/src/node/monitor-settings/monitor-settings-provider-impl.ts
  arduino-ide-extension/src/node/monitor-settings/monitor-settings-provider.ts
  arduino-ide-extension/src/node/monitor-settings/monitor-settings-utils.ts
  arduino-ide-extension/src/node/serial/monitor-client-provider.ts
  arduino-ide-extension/src/node/serial/serial-service-impl.ts
  arduino-ide-extension/src/node/web-socket/web-socket-provider-impl.ts
  arduino-ide-extension/src/node/web-socket/web-socket-provider.ts
  arduino-ide-extension/src/test/browser/fixtures/serial.ts
  arduino-ide-extension/src/test/node/monitor-settings-utils.test.ts
  arduino-ide-extension/src/test/node/serial-service-impl.test.ts
  i18n/en.json
  yarn.lock
Labels: type: enhancement, topic: code, topic: serial monitor

#1025 Fix monitor service id creation
  arduino-ide-extension/src/node/arduino-firmware-uploader-impl.ts
  arduino-ide-extension/src/node/monitor-manager.ts
Labels: topic: code, type: imperfection

#1046 #1031 Restored the Settings UI. Deferred model loading.
  arduino-ide-extension/src/browser/theia/preferences/preference-tree-generator.ts
Labels: type: enhancement, topic: code

#1035 Survey notification implementation
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/arduino-preferences.ts
  arduino-ide-extension/src/browser/contributions/survey-notification.ts
  arduino-ide-extension/src/common/protocol/survey-service.ts
  arduino-ide-extension/src/electron-main/arduino-electron-main-module.ts
  arduino-ide-extension/src/node/survey-service-impl.ts
  i18n/en.json
Labels: type: enhancement, topic: code

#1065 Can enable debug logging of the gRPC calls.
  arduino-ide-extension/src/browser/arduino-preferences.ts
  arduino-ide-extension/src/node/arduino-daemon-impl.ts
  i18n/en.json
Labels: type: enhancement, topic: code

#1074 flush on clear output buffer
  arduino-ide-extension/src/node/utils/simple-buffer.ts
Labels: topic: code, type: imperfection

#1040 #1032 failing upload flag for monitor mgr
  arduino-ide-extension/package.json
  arduino-ide-extension/src/node/arduino-firmware-uploader-impl.ts
  arduino-ide-extension/src/node/core-service-impl.ts
  arduino-ide-extension/src/node/monitor-manager-proxy-impl.ts
  arduino-ide-extension/src/node/monitor-manager.ts
  arduino-ide-extension/src/node/monitor-service.ts
Labels: topic: code, type: imperfection, topic: serial monitor

#1022 Disabled `MenuItem` `roles` on macOS.
  arduino-ide-extension/src/electron-browser/theia/core/electron-main-menu-factory.ts
Labels: topic: code, os: macos, type: imperfection

#1097 Sketchbook tree indentation
  arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-tree-widget.tsx
Labels: type: enhancement, topic: code, type: imperfection

#1103 bump arduino-cli version to 0.24.0
  arduino-ide-extension/package.json
Labels: type: enhancement, topic: infrastructure

#1104 Add missing 'Advanced' string
  arduino-ide-extension/src/browser/contributions/settings.ts
  i18n/en.json
Labels: topic: code, type: imperfection

#1116 Run "Arduino IDE" workflow on pull requests with any base branch
  .github/workflows/build.yml
Labels: type: enhancement, topic: infrastructure

#1113 Remove obsolete compilation error interpretations
  arduino-ide-extension/src/node/cli-error-parser.ts
  i18n/en.json
Labels: type: enhancement, topic: code

#1115 Enable "Arduino IDE" workflow use by contributors
  .github/workflows/build.yml
  electron/build/scripts/notarize.js
Labels: type: enhancement, topic: infrastructure

#1114 Only run "Arduino IDE" workflow on relevant changes
  .github/workflows/build.yml
Labels: type: enhancement, topic: infrastructure

#1095 Sketchbook icons colors
  arduino-ide-extension/src/browser/style/cloud-sketchbook-tree-icon-filled.svg
  arduino-ide-extension/src/browser/style/cloud-sketchbook-tree-icon.svg
  arduino-ide-extension/src/browser/style/cloud-sketchbook.css
  arduino-ide-extension/src/browser/style/sketchbook-tree-icon-filled.svg
  arduino-ide-extension/src/browser/style/sketchbook-tree-icon.svg
  arduino-ide-extension/src/browser/style/sketchbook.css
Labels: topic: code, type: imperfection
