Repository arduino/arduino-ide, pull requests merged in 2022-03, with the labels that each got.

#868 show represented file on MacOS
  arduino-ide-extension/src/browser/theia/workspace/workspace-service.ts
Labels: type: enhancement, topic: code, os: macos

#872 fix IDE updater commands
  arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx
  arduino-ide-extension/src/browser/contributions/help.ts
  arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-component.tsx
  arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx
  arduino-ide-extension/src/browser/ide-updater/ide-updater-commands.ts
  arduino-ide-extension/src/common/protocol/ide-updater.ts
  arduino-ide-extension/src/electron-main/ide-updater/ide-updater-impl.ts
  i18n/en.json
Labels: topic: code, type: imperfection

#878 Install Node.js 14.x on compose-full-changelog workflow
  .github/workflows/compose-full-changelog.yaml
Labels: topic: infrastructure, type: imperfection

#838 add PR template file
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: enhancement, topic: infrastructure

#880 Override the `RELOAD_REQUESTED_SIGNAL` correctly
  arduino-ide-extension/src/electron-main/theia/electron-main-application.ts
Labels: topic: code, type: imperfection

#886 Remove irrelevant trigger from "Compose full changelog" workflow
  .github/workflows/compose-full-changelog.yaml
Labels: type: enhancement, topic: infrastructure

#885 Add Linux AppImage to nightly build download links
  README.md
Labels: topic: documentation, type: enhancement

#887 Fix sketch name duplicates
  arduino-ide-extension/src/node/sketches-service-impl.ts
Labels: topic: code

#882 Remove dev tools menu item
  arduino-ide-extension/src/browser/contributions/help.ts
Labels: type: enhancement, topic: code

#891 Remove irrelevant statement from EULA
  electron/build/resources/eula.txt
Labels: topic: infrastructure, type: imperfection

#875 handling pagination in getting the sketches
  arduino-ide-extension/src/browser/create/create-api.ts
Labels: topic: code, type: imperfection

#883 Add privacy policy menu item
  arduino-ide-extension/src/browser/contributions/help.ts
  i18n/en.json
Labels: type: enhancement, topic: code

#901 Install oktokit in changelog workflow
  .github/workflows/compose-full-changelog.yaml
  arduino-ide-extension/src/electron-main/ide-updater/ide-updater-impl.ts
Labels: topic: infrastructure, type: imperfection

#915 Add links for other communication channels to the GitHub issue template chooser
  .github/ISSUE_TEMPLATE/config.yml
Labels: type: enhancement, topic: infrastructure

#916 Switch to form-based GitHub issue templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: type: enhancement, topic: infrastructure

#894 Automatically remove editors for deleted files
  arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx
Labels: topic: code, type: imperfection
