Repository arduino/arduino-ide, pull requests merged in 2022-08, with the labels that each got.

#1266 Use `0.25.1` CLI.
  arduino-ide-extension/package.json
Labels: topic: infrastructure, type: imperfection, topic: CLI

#1260 #575, #1175 Show 'progress' indicator during verify/upload
  arduino-ide-extension/src/browser/contributions/add-zip-library.ts
  arduino-ide-extension/src/browser/contributions/burn-bootloader.ts
  arduino-ide-extension/src/browser/contributions/contribution.ts
  arduino-ide-extension/src/browser/contributions/upload-sketch.ts
  arduino-ide-extension/src/browser/contributions/verify-sketch.ts
  arduino-ide-extension/src/browser/widgets/component-list/filterable-list-container.tsx
  arduino-ide-extension/src/common/protocol/core-service.ts
  arduino-ide-extension/src/common/protocol/installable.ts
  arduino-ide-extension/src/common/protocol/progressible.ts
  arduino-ide-extension/src/common/protocol/response-service.ts
  arduino-ide-extension/src/node/core-service-impl.ts
  arduino-ide-extension/src/node/grpc-progressible.ts
  i18n/en.json
Labels: type: enhancement, topic: code

#1265 High Contrast theme updates
  arduino-ide-extension/src/browser/style/arduino-select.css
  arduino-ide-extension/src/browser/style/boards-config-dialog.css
  arduino-ide-extension/src/browser/style/certificate-uploader-dialog.css
  arduino-ide-extension/src/browser/style/index.css
  arduino-ide-extension/src/browser/style/list-widget.css
  arduino-ide-extension/src/browser/style/main.css
  arduino-ide-extension/src/browser/style/sketchbook.css
Labels: topic: code, type: imperfection, topic: theme

#1216 Prevent board selector item labels to overflow
  arduino-ide-extension/src/browser/boards/boards-toolbar-item.tsx
  arduino-ide-extension/src/browser/style/boards-config-dialog.css
Labels: topic: code, type: imperfection

#1252 Custom colors clean up
  arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx
  arduino-ide-extension/src/browser/data/dark.color-theme.json
  arduino-ide-extension/src/browser/data/default.color-theme.json
  arduino-ide-extension/src/browser/style/boards-config-dialog.css
  arduino-ide-extension/src/browser/style/certificate-uploader-dialog.css
  arduino-ide-extension/src/browser/style/cloud-sketchbook.css
  arduino-ide-extension/src/browser/style/dialogs.css
  arduino-ide-extension/src/browser/style/editor.css
  arduino-ide-extension/src/browser/style/ide-updater-dialog.css
  arduino-ide-extension/src/browser/style/main.css
  arduino-ide-extension/src/browser/style/progress-bar.css
  arduino-ide-extension/src/browser/style/settings-dialog.css
  arduino-ide-extension/src/browser/style/sketchbook.css
  arduino-ide-extension/src/browser/style/user-fields-dialog.css
Labels: topic: code, topic: theme

#1280 Pinned `2dd8976` CLI in the IDE2.
  arduino-ide-extension/package.json
Labels: topic: infrastructure, topic: CLI

#1288 Set `XDG_CONFIG_HOME` env on Linux when not set.
  electron/build/patch/backend/main.js
Labels: topic: code, os: linux, type: imperfection

#1285 Sync sketch formatter configuration from source
  arduino-ide-extension/src/node/clang-formatter.ts
Labels: type: enhancement, topic: infrastructure, topic: code

#1296 Live change of theme from Preferences dropdown
  arduino-ide-extension/src/browser/dialogs/settings/settings-component.tsx
  arduino-ide-extension/src/browser/dialogs/settings/settings-dialog.tsx
Labels: type: enhancement, topic: code, topic: theme

#1230 Move Auto Format to the Edit menu
  arduino-ide-extension/src/browser/contributions/edit-contributions.ts
Labels: type: enhancement, topic: code, criticality: high

#1312 2.0.0-rc9.2
  arduino-ide-extension/package.json
  browser-app/package.json
  electron-app/package.json
  package.json
Labels: type: enhancement, topic: infrastructure

#1315 Use `Task` to build pinned CLI for IDE2.
  .github/workflows/build.yml
  .github/workflows/check-i18n-task.yml
  arduino-ide-extension/scripts/download-cli.js
  arduino-ide-extension/scripts/utils.js
Labels: type: enhancement, topic: code

#1310 Use the refactored CLI in IDE2
  arduino-ide-extension/package.json
Labels: type: enhancement, status: on hold, topic: CLI

#1321 Document clangd update procedure
  arduino-ide-extension/README.md
Labels: topic: documentation, type: enhancement, topic: language server

#1324 Use unmodified official ClangFormat configuration as base formatter configuration
  arduino-ide-extension/src/node/clang-formatter.ts
  arduino-ide-extension/src/node/default-formatter-config.json
  arduino-ide-extension/tsconfig.json
Labels: type: enhancement, topic: code

#1326 Change naming of nightly and snapshot builds
  electron/packager/config.js
Labels: topic: code, type: imperfection

#1325 #1142 Handle missing core when getting board user fields
  arduino-ide-extension/src/node/boards-service-impl.ts
Labels: topic: code, type: imperfection

#1311 Fix dialogs UI scalability
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/boards/boards-config-dialog.ts
  arduino-ide-extension/src/browser/boards/boards-config.tsx
  arduino-ide-extension/src/browser/dialogs/certificate-uploader/certificate-uploader-dialog.tsx
  arduino-ide-extension/src/browser/dialogs/firmware-uploader/firmware-uploader-dialog.tsx
  arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-component.tsx
  arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx
  arduino-ide-extension/src/browser/dialogs/settings/settings-component.tsx
  arduino-ide-extension/src/browser/dialogs/settings/settings-step-input.tsx
  arduino-ide-extension/src/browser/ide-updater/ide-updater-client-impl.ts
  arduino-ide-extension/src/browser/style/boards-config-dialog.css
  arduino-ide-extension/src/browser/style/certificate-uploader-dialog.css
  arduino-ide-extension/src/browser/style/dialogs.css
  arduino-ide-extension/src/browser/style/firmware-uploader-dialog.css
  arduino-ide-extension/src/browser/style/ide-updater-dialog.css
  arduino-ide-extension/src/browser/style/settings-dialog.css
  arduino-ide-extension/src/browser/style/settings-step-input.css
  arduino-ide-extension/src/common/protocol/ide-updater.ts
  arduino-ide-extension/src/electron-main/ide-updater/ide-updater-impl.ts
  i18n/en.json
Labels: topic: code, type: imperfection

#1339 Use more relevant page for "Help > Environment" menu item target
  arduino-ide-extension/src/browser/contributions/help.ts
Labels: topic: code, type: imperfection

#1340 Fix typos in log messages
  arduino-ide-extension/src/browser/contributions/compiler-errors.ts
  arduino-ide-extension/src/common/protocol/sketches-service-client-impl.ts
  arduino-ide-extension/src/node/core-client-provider.ts
  arduino-ide-extension/src/node/core-service-impl.ts
  scripts/i18n/transifex-pull.js
Labels: topic: code, type: imperfection

#1348 Install Arduino CLI build dependencies in all dependent workflows
  .github/workflows/build.yml
  .github/workflows/check-i18n-task.yml
  .github/workflows/i18n-nightly-push.yml
  .github/workflows/i18n-weekly-pull.yml
  .github/workflows/themes-weekly-pull.yml
Labels: topic: infrastructure, type: imperfection

#1345 Align functional max-min of scale stepper to actual max-min zoom level
  arduino-ide-extension/src/browser/dialogs/settings/settings-component.tsx
Labels: topic: code, type: imperfection

#1353 Error message if upload is not possible
  arduino-ide-extension/src/browser/contributions/contribution.ts
  arduino-ide-extension/src/browser/contributions/upload-sketch.ts
  i18n/en.json
Labels: type: enhancement, topic: code

#1358 Pinned 63f1e18 CLI.
  arduino-ide-extension/package.json
Labels: topic: CLI

#1361 #177, #1188 Implemented filter and update all for libs/boards
  arduino-ide-extension/package.json
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/arduino-preferences.ts
  arduino-ide-extension/src/browser/boards/boards-auto-installer.ts
  arduino-ide-extension/src/browser/boards/boards-list-widget.ts
  arduino-ide-extension/src/browser/boards/boards-widget-frontend-contribution.ts
  arduino-ide-extension/src/browser/contributions/check-for-ide-updates.ts
  arduino-ide-extension/src/browser/contributions/check-for-updates.ts
  arduino-ide-extension/src/browser/contributions/open-sketch-files.ts
  arduino-ide-extension/src/browser/ide-updater/ide-updater-commands.ts
  arduino-ide-extension/src/browser/library/library-list-widget.ts
  arduino-ide-extension/src/browser/style/list-widget.css
  arduino-ide-extension/src/browser/theia/preferences/preference-editor-widget.ts
  arduino-ide-extension/src/browser/widgets/component-list/component-list-item.tsx
  arduino-ide-extension/src/browser/widgets/component-list/component-list.tsx
  arduino-ide-extension/src/browser/widgets/component-list/filter-renderer.tsx
  arduino-ide-extension/src/browser/widgets/component-list/filterable-list-container.tsx
  arduino-ide-extension/src/browser/widgets/component-list/list-item-renderer.tsx
  arduino-ide-extension/src/browser/widgets/component-list/list-widget-frontend-contribution.ts
  arduino-ide-extension/src/browser/widgets/component-list/list-widget.tsx
  arduino-ide-extension/src/common/nls.ts
  arduino-ide-extension/src/common/protocol/arduino-component.ts
  arduino-ide-extension/src/common/protocol/boards-service.ts
  arduino-ide-extension/src/common/protocol/installable.ts
  arduino-ide-extension/src/common/protocol/library-service.ts
  arduino-ide-extension/src/common/protocol/progressible.ts
  arduino-ide-extension/src/common/protocol/searchable.ts
  arduino-ide-extension/src/node/boards-service-impl.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_grpc_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_grpc_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/common_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/common_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/lib_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/lib_pb.js
  arduino-ide-extension/src/node/library-service-impl.ts
  arduino-ide-extension/src/test/browser/fixtures/boards.ts
  i18n/en.json
Labels: type: enhancement, topic: code

#1375 #1210 Fixed highlighting of non-unicode chars in Output
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/theia/output/output-editor-factory.ts
  arduino-ide-extension/src/browser/theia/output/output-widget.ts
Labels: topic: code, type: imperfection, topic: theia
