Repository arduino/arduino-ide, pull requests merged in 2022-04, with the labels that each got.

#943 Correctly print backslash-escaped characters
  arduino-ide-extension/src/browser/serial/monitor/serial-monitor-send-output.tsx
Labels: topic: code, type: imperfection, topic: serial monitor

#918 Improve condition to recognise read-only sketches
  arduino-ide-extension/src/browser/utils/constants.ts
  arduino-ide-extension/src/common/protocol/sketches-service-client-impl.ts
Labels: topic: code

#941 Enable language packs
  arduino-ide-extension/package.json
  arduino-ide-extension/src/browser/contributions/add-zip-library.ts
  arduino-ide-extension/src/node/arduino-ide-backend-module.ts
  arduino-ide-extension/src/node/arduino-localization-contribution.ts
  electron/build/template-package.json
  electron/packager/index.js
  package.json
Labels: type: enhancement, topic: infrastructure

#953 Use electron reload command when changing language
  arduino-ide-extension/src/browser/dialogs/settings/settings.tsx
Labels: topic: code, type: imperfection

#957 Set the current language on the localization provider
  arduino-ide-extension/src/browser/dialogs/settings/settings.tsx
  arduino-ide-extension/src/node/arduino-daemon-impl.ts
Labels: topic: code, type: imperfection

#946 Allow to close files in certain folders
  arduino-ide-extension/src/browser/theia/core/application-shell.ts
Labels: topic: code

#955 2.0.0-rc6
  arduino-ide-extension/package.json
  browser-app/package.json
  electron-app/package.json
  package.json
Labels: type: enhancement, topic: infrastructure

#939 Save all open editors before running `Save As`
  arduino-ide-extension/src/browser/contributions/save-as-sketch.ts
Labels: topic: code, type: imperfection
