Repository arduino/arduino-ide, pull requests merged in 2022-09, with the labels that each got.

#1377 #1365 Show ports if has recognized board attached to it
  arduino-ide-extension/src/browser/boards/boards-config.tsx
  arduino-ide-extension/src/browser/boards/boards-service-provider.ts
  arduino-ide-extension/src/common/protocol/boards-service.ts
Labels: topic: code, type: imperfection

#1391 #1390 Coerce a semver when calculating updatables
  arduino-ide-extension/src/common/protocol/installable.ts
Labels: topic: code, type: imperfection

#1385 #1380 #1381 #1387 Improved the scrolling UX in list widgets
  arduino-ide-extension/src/browser/style/list-widget.css
  arduino-ide-extension/src/browser/widgets/component-list/component-list.tsx
  arduino-ide-extension/src/browser/widgets/component-list/filterable-list-container.tsx
Labels: topic: code, type: imperfection

#1399 Prepared `2.0.0-rc9.3`.
  arduino-ide-extension/package.json
  browser-app/package.json
  electron-app/package.json
  package.json
Labels: type: enhancement, topic: infrastructure

#1407 Add instructions for accessing IDE's advanced settings
  docs/advanced-usage.md
Labels: topic: documentation, type: enhancement

#1413 Time format in Serial Monitor changed. Fixes #580
  arduino-ide-extension/src/browser/serial/monitor/serial-monitor-send-output.tsx
Labels: topic: code, type: imperfection

#1411 Prepare 2.0.0-rc9.4
  arduino-ide-extension/package.json
  browser-app/package.json
  electron-app/package.json
  package.json
Labels: type: enhancement, topic: infrastructure, topic: CLI

#1424 Remove table of nightly build links from readme
  README.md
Labels: topic: documentation, type: enhancement

#1430 Remove obsolete fragment identifier from IDE manual download link
  arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx
Labels: type: enhancement, topic: code

#1402 #572 Can send message to the monitor with `Enter`
  arduino-ide-extension/src/browser/serial/monitor/serial-monitor-send-input.tsx
  i18n/en.json
Labels: topic: code, type: imperfection

#1409 #39 Avoid deleting the workspace when it's still in use
  .eslintrc.js
  .vscode/launch.json
  .vscode/tasks.json
  arduino-ide-extension/package.json
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/boards/boards-config.tsx
  arduino-ide-extension/src/browser/boards/boards-service-provider.ts
  arduino-ide-extension/src/browser/contributions/delete-sketch.ts
  arduino-ide-extension/src/browser/contributions/save-as-sketch.ts
  arduino-ide-extension/src/browser/contributions/sketch-files-tracker.ts
  arduino-ide-extension/src/browser/contributions/startup-task.ts
  arduino-ide-extension/src/browser/theia/core/browser-main-menu-factory.ts
  arduino-ide-extension/src/browser/theia/core/browser-menu-module.ts
  arduino-ide-extension/src/browser/theia/core/browser-window-module.ts
  arduino-ide-extension/src/browser/theia/core/default-window-service.ts
  arduino-ide-extension/src/browser/theia/core/window-service-ext.ts
  arduino-ide-extension/src/browser/theia/workspace/workspace-service.ts
  arduino-ide-extension/src/browser/widgets/sketchbook/startup-task.ts
  arduino-ide-extension/src/common/protocol/sketches-service-client-impl.ts
  arduino-ide-extension/src/common/protocol/sketches-service.ts
  arduino-ide-extension/src/electron-browser/theia/core/electron-window-service.ts
  arduino-ide-extension/src/electron-common/startup-task.ts
  arduino-ide-extension/src/electron-main/arduino-electron-main-module.ts
  arduino-ide-extension/src/electron-main/electron-main-window-service-ext-impl.ts
  arduino-ide-extension/src/electron-main/theia/electron-main-window-service.ts
  arduino-ide-extension/src/electron-main/theia/theia-electron-window.ts
  arduino-ide-extension/src/electron-main/theia/window.ts
  arduino-ide-extension/src/node/arduino-ide-backend-module.ts
  arduino-ide-extension/src/node/sketches-service-impl.ts
  arduino-ide-extension/src/node/theia/filesystem/nsfw-watcher/index.ts
  arduino-ide-extension/src/node/theia/filesystem/nsfw-watcher/nsfw-bindings.ts
  arduino-ide-extension/src/node/theia/filesystem/nsfw-watcher/nsfw-filesystem-service.ts
  browser-app/package.json
  browser-app/webpack.config.js
  docs/internal/release-procedure.md
  electron/packager/index.js
  package.json
  scripts/update-version.js
Labels: topic: code, type: imperfection

#1410 Use IPC message to focus on serial plotter window
  arduino-ide-extension/src/browser/serial/plotter/plotter-frontend-contribution.ts
  arduino-ide-extension/src/common/ipc-communication.ts
  arduino-ide-extension/src/electron-main/theia/electron-main-application.ts
Labels: topic: code, type: imperfection

#1450 #1343 Disabled the tokenizer after 500 chars.
  electron-app/package.json
Labels: topic: code, type: imperfection

#1415 Show user fields dialog again if upload fails
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/contributions/upload-sketch.ts
  arduino-ide-extension/src/browser/contributions/user-fields.ts
Labels: type: enhancement, topic: code

#1382 Move primary buttons on the right of the dialogs
  arduino-ide-extension/src/browser/dialogs/settings/settings-dialog.tsx
  arduino-ide-extension/src/browser/library/library-list-widget.ts
  arduino-ide-extension/src/browser/style/settings-dialog.css
  arduino-ide-extension/src/browser/theia/workspace/workspace-input-dialog.ts
Labels: topic: code, type: imperfection

#1446 Serial Monitor autoscroll only makes bottom line partially visible #972
  arduino-ide-extension/src/browser/style/monitor.css
Labels: topic: code, type: imperfection, topic: serial monitor

#1465 #1441 Fix input background in Firmware Updater dialog
  arduino-ide-extension/src/browser/style/firmware-uploader-dialog.css
Labels: topic: code, type: imperfection

#1448 #1445 Ensure `directories.user` exists.
  arduino-ide-extension/src/node/config-service-impl.ts
Labels: topic: code, type: imperfection

#1474 Avoid new line if 3rd party URLs text is too long
  arduino-ide-extension/src/browser/style/settings-dialog.css
Labels: topic: code, type: imperfection

#1478 #989 Listen on keyboard layout changes from the OS
  arduino-ide-extension/src/electron-main/arduino-electron-main-module.ts
Labels: topic: code, type: imperfection, topic: theia

#1449 #1431 Add missing translations
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/boards/boards-config.tsx
  arduino-ide-extension/src/browser/contributions/board-selection.ts
  arduino-ide-extension/src/browser/dialogs/settings/settings-component.tsx
  arduino-ide-extension/src/browser/serial/plotter/plotter-frontend-contribution.ts
  arduino-ide-extension/src/browser/style/list-widget.css
  arduino-ide-extension/src/browser/theia/search-in-workspace/search-in-workspace-result-tree-widget.ts
  arduino-ide-extension/src/browser/theia/search-in-workspace/search-in-workspace-widget.tsx
  arduino-ide-extension/src/browser/widgets/component-list/list-item-renderer.tsx
  arduino-ide-extension/src/common/protocol/boards-service.ts
  arduino-ide-extension/src/common/protocol/core-service.ts
  arduino-ide-extension/src/node/i18n/arduino-localization-contribution.ts
  arduino-ide-extension/src/node/i18n/localization-backend-contribution.ts
  electron-app/patch/frontend/index.js
  electron/build/template-package.json
  electron/packager/index.js
  i18n/en.json
  package.json
Labels: topic: code, type: imperfection

#1490 Initialise the IDE updater even when 'checkForUpdates' preference is false
  arduino-ide-extension/src/browser/contributions/check-for-ide-updates.ts
Labels: topic: code, type: imperfection

#1479 Avoid intellisense widgets being covered by the bottom panel
  arduino-ide-extension/src/browser/style/main.css
Labels: topic: code, type: imperfection

#1472 Dialog focus
  arduino-ide-extension/src/browser/boards/boards-service-provider.ts
  arduino-ide-extension/src/browser/contributions/upload-sketch.ts
  arduino-ide-extension/src/browser/contributions/user-fields.ts
  arduino-ide-extension/src/browser/dialogs/certificate-uploader/certificate-uploader-dialog.tsx
  arduino-ide-extension/src/browser/dialogs/firmware-uploader/firmware-uploader-dialog.tsx
  arduino-ide-extension/src/browser/dialogs/user-fields/user-fields-component.tsx
  arduino-ide-extension/src/browser/dialogs/user-fields/user-fields-dialog.tsx
  i18n/en.json
Labels: type: enhancement, topic: code
