Repository arduino/arduino-ide, pull requests merged in 2022-12, with the labels that each got.

#1739 Bump version metadata post release: 2.0.4
  arduino-ide-extension/package.json
  electron-app/package.json
  package.json
Labels: type: enhancement, topic: infrastructure

#1738 Fix formatting of generated release notes
  .github/workflows/build.yml
Labels: topic: infrastructure, type: imperfection

#1744 fix: `Preferences` menu enablement defect
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/contributions/open-settings.ts
Labels: topic: code, type: imperfection

#1743 fix: theme service binding
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/theia/core/theming.ts
  arduino-ide-extension/src/browser/utils/window.ts
Labels: topic: code, type: imperfection

#1745 Restore certificate check compatibility w/ RC2-40-CBC encrypted PKS#12
  .github/workflows/check-certificates.yml
Labels: topic: infrastructure, type: imperfection

#1746 feat: show the selected board config value on menu
  arduino-ide-extension/src/browser/boards/boards-data-menu-updater.ts
Labels: type: enhancement, topic: code

#1748 fix: list view filtering when opening the view
  arduino-ide-extension/src/browser/widgets/component-list/filterable-list-container.tsx
  arduino-ide-extension/src/browser/widgets/component-list/list-widget.tsx
Labels: topic: code, type: imperfection

#1758 Fix corruption of incoming UTF-8-encoded serial data
  arduino-ide-extension/src/node/monitor-service.ts
Labels: topic: code, type: imperfection

#1750 fix: menu item enablement issues
  arduino-ide-extension/src/browser/contributions/contribution.ts
  arduino-ide-extension/src/browser/contributions/examples.ts
  arduino-ide-extension/src/browser/contributions/interface-scale.ts
  arduino-ide-extension/src/browser/contributions/new-cloud-sketch.ts
  arduino-ide-extension/src/browser/contributions/open-settings.ts
  arduino-ide-extension/src/browser/contributions/upload-certificate.ts
  arduino-ide-extension/src/browser/contributions/upload-firmware.ts
  arduino-ide-extension/src/browser/contributions/upload-sketch.ts
  arduino-ide-extension/src/browser/contributions/user-fields.ts
  arduino-ide-extension/src/browser/contributions/verify-sketch.ts
  arduino-ide-extension/src/browser/theia/core/common-frontend-contribution.ts
Labels: type: enhancement, topic: code, type: imperfection

#1757 build: use a local npm registry for app packaging
  .eslintrc.js
  arduino-ide-extension/src/browser/dialogs/cloud-share-sketch-dialog.tsx
  arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-tree-widget.tsx
  electron/.gitignore
  electron/build/template-package.json
  electron/packager/index.js
  electron/packager/npm-registry/config.yml
  electron/packager/package.json
  electron/packager/test/utils.test.js
  electron/packager/yarn.lock
  package.json
  yarn.lock
Labels: type: enhancement, topic: infrastructure

#1778 Remove trailing colon when parsing the protocol from URL
  arduino-ide-extension/src/common/protocol/config-service.ts
Labels: topic: code, type: imperfection

#1776 Replace socks with socks5 in proxy protocol
  arduino-ide-extension/src/browser/dialogs/settings/settings-component.tsx
Labels: topic: code, type: imperfection, topic: CLI

#1774 feat: configure sketchbook location without restart
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/config/config-service-client.ts
  arduino-ide-extension/src/browser/contributions/add-zip-library.ts
  arduino-ide-extension/src/browser/contributions/archive-sketch.ts
  arduino-ide-extension/src/browser/contributions/board-selection.ts
  arduino-ide-extension/src/browser/contributions/contribution.ts
  arduino-ide-extension/src/browser/contributions/examples.ts
  arduino-ide-extension/src/browser/contributions/include-library.ts
  arduino-ide-extension/src/browser/contributions/open-sketch.ts
  arduino-ide-extension/src/browser/contributions/save-as-sketch.ts
  arduino-ide-extension/src/browser/contributions/sketchbook.ts
  arduino-ide-extension/src/browser/dialogs/settings/settings.ts
  arduino-ide-extension/src/browser/local-cache/local-cache-fs-provider.ts
  arduino-ide-extension/src/browser/menu/arduino-menus.ts
  arduino-ide-extension/src/browser/notification-center.ts
  arduino-ide-extension/src/browser/theia/core/tab-bar-decorator.ts
  arduino-ide-extension/src/browser/theia/markers/problem-manager.ts
  arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-tree-model.ts
  arduino-ide-extension/src/common/protocol/config-service.ts
  arduino-ide-extension/src/common/protocol/notification-service.ts
  arduino-ide-extension/src/common/protocol/sketches-service-client-impl.ts
  arduino-ide-extension/src/electron-browser/theia/core/electron-main-menu-factory.ts
  arduino-ide-extension/src/node/clang-formatter.ts
  arduino-ide-extension/src/node/config-service-impl.ts
  arduino-ide-extension/src/node/core-client-provider.ts
  arduino-ide-extension/src/node/notification-service-server.ts
  arduino-ide-extension/src/node/sketches-service-impl.ts
  i18n/en.json
Labels: type: enhancement, topic: code, type: imperfection
