Repository arduino/arduino-ide, pull requests merged in 2022-10, with the labels that each got.

#1507 Correct text of "INSTALLED" label in Library/Boards Manager
  arduino-ide-extension/src/browser/widgets/component-list/list-item-renderer.tsx
  i18n/en.json
Labels: topic: code, type: imperfection

#1333 #53 Refresh menus when opening example/recent fails.
  arduino-ide-extension/src/browser/contributions/examples.ts
  arduino-ide-extension/src/browser/contributions/new-sketch.ts
  arduino-ide-extension/src/browser/contributions/open-recent-sketch.ts
  arduino-ide-extension/src/browser/contributions/open-sketch.ts
  arduino-ide-extension/src/browser/contributions/save-sketch.ts
  arduino-ide-extension/src/browser/contributions/sketchbook.ts
  arduino-ide-extension/src/browser/theia/core/about-dialog.ts
  arduino-ide-extension/src/common/protocol/core-service.ts
  arduino-ide-extension/src/common/protocol/sketches-service.ts
  arduino-ide-extension/src/node/arduino-ide-backend-module.ts
  arduino-ide-extension/src/node/config-service-impl.ts
  arduino-ide-extension/src/node/core-client-provider.ts
  arduino-ide-extension/src/node/examples-service-impl.ts
  arduino-ide-extension/src/node/sketches-service-impl.ts
Labels: topic: code, type: imperfection

#1516 Bump arduino-serial-plotter-webapp dependency to 0.2.0
  arduino-ide-extension/package.json
  yarn.lock
Labels: topic: infrastructure

#1512 Update library dependency installation dialog response indexes
  arduino-ide-extension/src/browser/library/library-list-widget.ts
Labels: topic: code, type: imperfection

#1519 Bump built-in example sketches version to 1.10.0
  arduino-ide-extension/scripts/download-examples.js
Labels: type: enhancement, topic: infrastructure

#1418 #1084, #1156 Various library/platform index update fixes
  arduino-ide-extension/package.json
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/boards/boards-config.tsx
  arduino-ide-extension/src/browser/contributions/indexes-update-progress.ts
  arduino-ide-extension/src/browser/contributions/update-indexes.ts
  arduino-ide-extension/src/browser/notification-center.ts
  arduino-ide-extension/src/browser/widgets/component-list/list-widget.tsx
  arduino-ide-extension/src/common/protocol/core-service.ts
  arduino-ide-extension/src/common/protocol/notification-service.ts
  arduino-ide-extension/src/node/board-discovery.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/common_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/common_pb.js
  arduino-ide-extension/src/node/core-client-provider.ts
  arduino-ide-extension/src/node/grpc-progressible.ts
  arduino-ide-extension/src/node/notification-service-server.ts
  i18n/en.json
Labels: topic: code, status: on hold, type: imperfection, topic: CLI

#1528 #1525 Removed the `real_name` of the libraries
  arduino-ide-extension/package.json
  arduino-ide-extension/src/common/protocol/library-service.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/lib_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/lib_pb.js
  arduino-ide-extension/src/node/examples-service-impl.ts
  arduino-ide-extension/src/node/library-service-impl.ts
Labels: topic: code, type: imperfection

#1502 Limit interface scale
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/contributions/edit-contributions.ts
  arduino-ide-extension/src/browser/contributions/interface-scale.ts
  arduino-ide-extension/src/browser/dialogs/settings/settings-component.tsx
Labels: topic: code, type: imperfection

#1530 #1529 Avoid using `reportResult` if installing lib/core
  arduino-ide-extension/src/node/core-client-provider.ts
  arduino-ide-extension/src/node/grpc-progressible.ts
Labels: topic: code, type: imperfection

#1481 #1442 Link resolver for lib/boards manager
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/boards/boards-widget-frontend-contribution.ts
  arduino-ide-extension/src/browser/library/library-widget-frontend-contribution.ts
  arduino-ide-extension/src/browser/widgets/component-list/list-widget-frontend-contribution.ts
  arduino-ide-extension/src/common/protocol/boards-service.ts
  arduino-ide-extension/src/common/protocol/library-service.ts
  arduino-ide-extension/src/common/protocol/searchable.ts
  arduino-ide-extension/src/test/common/searchable.test.ts
Labels: topic: code, type: imperfection, topic: CLI

#1517 Fix status bar clipped in minimal state
  arduino-ide-extension/src/browser/style/index.css
Labels: topic: code, type: imperfection

#1531 #1526 Ensure exact match when installing `Arduino_BuiltIn` on the first IDE2 startup
  arduino-ide-extension/src/browser/contributions/first-startup-installer.ts
Labels: topic: code, type: imperfection

#1504 Better tooltips.
  arduino-ide-extension/src/browser/style/main.css
Labels: topic: code, type: imperfection, topic: theia

#1471 Retain Library/Boards Manager installation interface using version menu
  arduino-ide-extension/src/browser/style/list-widget.css
  arduino-ide-extension/src/browser/widgets/component-list/component-list-item.tsx
Labels: type: enhancement, topic: code

#1541 Put Arduino libs on top of the Library Manager
  arduino-ide-extension/src/browser/widgets/component-list/filterable-list-container.tsx
  arduino-ide-extension/src/browser/widgets/component-list/list-widget.tsx
Labels: type: enhancement, topic: code

#1520 Fix boards listing
  arduino-ide-extension/src/browser/boards/boards-data-menu-updater.ts
  arduino-ide-extension/src/browser/contributions/board-selection.ts
  arduino-ide-extension/src/browser/contributions/sketch-control.ts
  arduino-ide-extension/src/common/protocol/boards-service.ts
  arduino-ide-extension/src/node/boards-service-impl.ts
Labels: topic: code, type: imperfection

#1545 #573 Listen on the client's port change event
  arduino-ide-extension/src/browser/boards/boards-config.tsx
  arduino-ide-extension/src/browser/boards/boards-service-provider.ts
Labels: topic: code, type: imperfection

#1521 Let CSS do the uppercase transformation.
  arduino-ide-extension/src/browser/style/index.css
  arduino-ide-extension/src/browser/style/list-widget.css
  arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-tree-widget.tsx
  arduino-ide-extension/src/browser/widgets/component-list/list-item-renderer.tsx
  i18n/en.json
Labels: type: enhancement, topic: code

#1401 Adjust library installation dialog buttons style
  arduino-ide-extension/src/browser/library/library-list-widget.ts
  arduino-ide-extension/src/browser/style/index.css
  i18n/en.json
Labels: topic: code, type: imperfection

#1564 Allow uploads without port selection
  arduino-ide-extension/src/browser/boards/boards-service-provider.ts
  arduino-ide-extension/src/browser/contributions/user-fields.ts
Labels: topic: code, type: imperfection

#1569 Fix #1566 : Port submenu section heading show at top
  arduino-ide-extension/src/browser/contributions/board-selection.ts
Labels: topic: code, type: imperfection

#1547 Let the user edit the font size settings with the keyboard
  arduino-ide-extension/src/browser/dialogs/settings/settings-component.tsx
  arduino-ide-extension/src/browser/dialogs/settings/settings-step-input.tsx
  arduino-ide-extension/src/browser/style/settings-step-input.css
Labels: type: enhancement, topic: code

#1570 #1544 Changed the daemon output from `json` to `text`
  arduino-ide-extension/src/node/arduino-daemon-impl.ts
Labels: type: enhancement, topic: code, topic: CLI

#1571 chore: Use `0.28.0` CLI in IDE2.
  arduino-ide-extension/package.json
Labels: type: enhancement, topic: CLI

#1562 #1404 Added Message History to Serial Monitor
  arduino-ide-extension/src/browser/serial/monitor/serial-monitor-send-input.tsx
Labels: type: enhancement, topic: code, topic: serial monitor

#1568 Prevent layout shift on hover in libs/board manager
  arduino-ide-extension/src/browser/widgets/component-list/component-list-item.tsx
  arduino-ide-extension/src/browser/widgets/component-list/component-list.tsx
  arduino-ide-extension/src/browser/widgets/component-list/list-item-renderer.tsx
Labels: type: enhancement, topic: code

#1559 Added an optional user modifiable default sketch file when creating a new project.
  arduino-ide-extension/src/browser/arduino-preferences.ts
  arduino-ide-extension/src/node/sketches-service-impl.ts
  i18n/en.json
Labels: type: enhancement, topic: code

#1589 Bump version metadata post release
  arduino-ide-extension/package.json
  electron-app/package.json
  package.json
Labels: type: enhancement, topic: infrastructure
