Repository arduino/arduino-ide, pull requests merged in 2022-02, with the labels that each got.

#792 When selecting new port that matches board type, also check match of protocol
  arduino-ide-extension/src/browser/boards/boards-service-provider.ts
Labels: topic: code, type: imperfection

#780 Restore open sketches on startup
  arduino-ide-extension/src/browser/arduino-workspace-resolver.ts
  arduino-ide-extension/src/electron-main/theia/electron-main-application.ts
Labels: topic: code

#791 Update Theia to 1.22.1
  .github/workflows/build.yml
  .github/workflows/check-i18n-task.yml
  .github/workflows/i18n-nightly-push.yml
  .github/workflows/i18n-weekly-pull.yml
  .vscode/launch.json
  BUILDING.md
  arduino-ide-extension/package.json
  arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx
  arduino-ide-extension/src/browser/contributions/about.ts
  arduino-ide-extension/src/browser/contributions/add-file.ts
  arduino-ide-extension/src/browser/contributions/add-zip-library.ts
  arduino-ide-extension/src/browser/contributions/archive-sketch.ts
  arduino-ide-extension/src/browser/contributions/board-selection.ts
  arduino-ide-extension/src/browser/contributions/close.ts
  arduino-ide-extension/src/browser/contributions/open-sketch-external.ts
  arduino-ide-extension/src/browser/contributions/open-sketch.ts
  arduino-ide-extension/src/browser/contributions/quit-app.ts
  arduino-ide-extension/src/browser/contributions/save-as-sketch.ts
  arduino-ide-extension/src/browser/serial/plotter/plotter-frontend-contribution.ts
  arduino-ide-extension/src/browser/theia/debug/debug-session-manager.ts
  arduino-ide-extension/src/browser/theia/workspace/workspace-delete-handler.ts
  arduino-ide-extension/src/browser/theia/workspace/workspace-service.ts
  arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-widget-contribution.ts
  arduino-ide-extension/src/electron-browser/electron-window-service.ts
  arduino-ide-extension/src/electron-browser/theia/core/electron-main-menu-factory.ts
  arduino-ide-extension/src/electron-main/theia/electron-main-application.ts
  browser-app/package.json
  docs/internal/Arm.md
  docs/internal/Ubuntu.md
  electron-app/package.json
  electron/build/template-package.json
  electron/packager/config.js
  electron/packager/index.js
  electron/packager/package.json
  package.json
  yarn.lock
Labels: type: enhancement, topic: infrastructure

#820 Update arduino-cli to 0.21.0
  arduino-ide-extension/package.json
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_grpc_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_grpc_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/common_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/common_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/compile_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/compile_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/upload_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/upload_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/monitor/v1/monitor_grpc_pb.js
Labels: type: enhancement, topic: infrastructure

#826 Fix board options not shown for manually installed platforms
  arduino-ide-extension/src/browser/boards/boards-data-store.ts
Labels: topic: code, type: imperfection

#834 Add gRPC user agent
  arduino-ide-extension/src/node/grpc-client-provider.ts
Labels: type: enhancement, topic: code

#837 Fix version retrieval in node process
  arduino-ide-extension/src/node/grpc-client-provider.ts
Labels: topic: code, type: imperfection

#797 Check for IDE update at startup
  .github/workflows/build.yml
  arduino-ide-extension/package.json
  arduino-ide-extension/scripts/compose-changelog.js
  arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/arduino-preferences.ts
  arduino-ide-extension/src/browser/components/ProgressBar.tsx
  arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-component.tsx
  arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx
  arduino-ide-extension/src/browser/dialogs/settings/settings-component.tsx
  arduino-ide-extension/src/browser/dialogs/settings/settings.tsx
  arduino-ide-extension/src/browser/ide-updater/ide-updater-client-impl.ts
  arduino-ide-extension/src/browser/ide-updater/ide-updater-commands.ts
  arduino-ide-extension/src/browser/style/ide-logo.png
  arduino-ide-extension/src/browser/style/ide-updater-dialog.css
  arduino-ide-extension/src/browser/style/index.css
  arduino-ide-extension/src/browser/style/progress-bar.css
  arduino-ide-extension/src/common/protocol/ide-updater.ts
  arduino-ide-extension/src/electron-main/arduino-electron-main-module.ts
  arduino-ide-extension/src/node/grpc-client-provider.ts
  arduino-ide-extension/src/node/ide-updater/ide-updater-impl.ts
  browser-app/package.json
  electron-app/package.json
  electron/build/template-package.json
  electron/packager/config.js
  electron/packager/index.js
  electron/packager/utils.js
  electron/packager/yarn.lock
  i18n/en.json
  yarn.lock
Labels: topic: code

#846 IDE updater bugfixes
  .github/workflows/build.yml
  arduino-ide-extension/src/node/ide-updater/ide-updater-impl.ts
  electron/build/scripts/notarize.js
  electron/build/template-package.json
  electron/packager/config.js
  electron/packager/index.js
  electron/packager/package.json
  electron/packager/utils.js
  electron/packager/yarn.lock
Labels: topic: code, type: imperfection

#835 Enable opening the IDE from finder/explorer
  arduino-ide-extension/src/electron-main/theia/electron-main-application.ts
  electron/build/template-package.json
Labels: topic: code, os: windows, os: macos

#860 Disable autodownload of updates on startup
  arduino-ide-extension/src/electron-main/arduino-electron-main-module.ts
  arduino-ide-extension/src/electron-main/ide-updater/ide-updater-impl.ts
Labels: topic: code, type: imperfection

#865 Add preference to set a custom update url
  arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx
  arduino-ide-extension/src/browser/arduino-preferences.ts
  arduino-ide-extension/src/common/protocol/ide-updater.ts
  arduino-ide-extension/src/electron-main/ide-updater/ide-updater-impl.ts
Labels: type: enhancement, topic: code
