Repository arduino/arduino-ide, pull requests merged in 2022-01, with the labels that each got.

#706 Improve build instructions
  BUILDING.md
Labels: topic: documentation, type: enhancement

#749 Update development docs for current repository
  docs/internal/Arm.md
  docs/internal/Ubuntu.md
Labels: topic: documentation, type: imperfection

#748 Correct minor typos in UI text and documentation
  BUILDING.md
  arduino-ide-extension/src/browser/boards/boards-config-dialog.ts
  arduino-ide-extension/src/browser/contributions/open-sketch.ts
  arduino-ide-extension/src/browser/contributions/upload-firmware.ts
  arduino-ide-extension/src/browser/dialogs/firmware-uploader/firmware-uploader-component.tsx
  arduino-ide-extension/src/browser/serial/monitor/serial-monitor-send-input.tsx
  docs/README.md
  docs/internal/Arm.md
  i18n/en.json
Labels: topic: documentation, topic: code, type: imperfection

#751 Remove stray brace from compilation error output
  arduino-ide-extension/src/node/core-service-impl.ts
Labels: topic: code, type: imperfection

#738 Update arduino-language-server to 0.6.0 and clangd to 13.0.0
  arduino-ide-extension/package.json
  arduino-ide-extension/scripts/download-ls.js
  arduino-ide-extension/scripts/downloader.js
  arduino-ide-extension/src/node/executable-service-impl.ts
  arduino-ide-extension/src/test/node/exec-util.test.ts
Labels: type: enhancement, topic: infrastructure, topic: language server

#782 Fix compose full changelog workflow
  .github/workflows/compose-full-changelog.yaml
Labels: topic: infrastructure, type: imperfection

#783 Fix compose-changelog.js overwriting itself when called with no arguments
  arduino-ide-extension/scripts/compose-changelog.js
Labels: topic: infrastructure, type: imperfection
