Repository arduino/arduino-ide, pull requests merged in 2023-10, with the labels that each got.

#2242 fix: use board+port at startup if it's restored
  arduino-ide-extension/src/browser/contributions/debug.ts
  arduino-ide-extension/src/browser/contributions/examples.ts
  arduino-ide-extension/src/browser/contributions/include-library.ts
  arduino-ide-extension/src/browser/contributions/selected-board.ts
Labels: topic: code, type: imperfection

#2092 test: run cloud sketches tests on the CI
  .eslintrc.js
  .github/workflows/build.yml
  arduino-ide-extension/src/browser/create/create-api.ts
  arduino-ide-extension/src/browser/create/typings.ts
  arduino-ide-extension/src/test/browser/create-api.slow-test.ts
Labels: type: enhancement, topic: code, topic: cloud

#2248 Update manual release procedure documentation to reflect implementation of automated builds for macOS ARM
  docs/internal/release-procedure.md
  package.json
  scripts/merge-channel-files.js
Labels: topic: documentation, type: enhancement

#2251 test: relax accessible sketch path test condition
  arduino-ide-extension/src/test/node/sketches-service-impl.slow-test.ts
Labels: topic: code

#2253 Make Linux build in a container for compatibility with older distros
  .github/workflows/assets/linux.Dockerfile
  .github/workflows/build.yml
  .github/workflows/check-containers.yml
  .github/workflows/push-container-images.yml
Labels: topic: infrastructure, os: linux, type: imperfection

#2252 chore(deps): update dependencies
  arduino-ide-extension/package.json
  arduino-ide-extension/scripts/download-cli.js
  arduino-ide-extension/scripts/download-examples.js
  arduino-ide-extension/scripts/download-fwuploader.js
  arduino-ide-extension/scripts/download-ls.js
  arduino-ide-extension/scripts/downloader.js
  arduino-ide-extension/scripts/generate-protocol.js
  arduino-ide-extension/scripts/utils.js
  arduino-ide-extension/src/browser/theia/workspace/workspace-input-dialog.ts
  arduino-ide-extension/src/electron-browser/preload.ts
  arduino-ide-extension/src/node/board-discovery.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_pb.js
  arduino-ide-extension/src/node/grpc-progressible.ts
  arduino-ide-extension/src/test/browser/create-api.slow-test.ts
  electron-app/package.json
  yarn.lock
Labels: topic: code, topic: security, type: imperfection

#2260 adding a hyperlink to the README
  README.md
Labels: topic: documentation, type: enhancement

#2261 Correct conditional logic for publishing steps of build workflow
  .github/workflows/build.yml
Labels: topic: infrastructure, type: imperfection

#2258 chore(doc): update main screenshot in the readme
  static/screenshot.png
Labels: topic: documentation, type: enhancement
