Repository arduino/arduino-ide, pull requests merged in 2023-07, with the labels that each got.

#2128 chore(version): updated the version to `2.1.2`
  arduino-ide-extension/package.json
  electron-app/package.json
  package.json
Labels: topic: code

#2101 fix: include all log `args` in the log message
  arduino-ide-extension/src/node/arduino-daemon-impl.ts
  electron/build/patch/backend/main.js
Labels: topic: code, type: imperfection

#2153 Clean localization data files before pulling from Transifex
  scripts/i18n/transifex-pull.js
Labels: topic: infrastructure, type: imperfection
