Repository arduino/arduino-ide, pull requests merged in 2023-02, with the labels that each got.

#1859 Add leading+trailing line break to "Copy for Forum" content
  arduino-ide-extension/src/browser/contributions/edit-contributions.ts
Labels: type: enhancement, topic: code

#1803 fix: show board info based on the selected port
  arduino-ide-extension/src/browser/boards/boards-config.tsx
  arduino-ide-extension/src/browser/contributions/board-selection.ts
  arduino-ide-extension/src/common/protocol/boards-service.ts
  arduino-ide-extension/src/test/common/boards-service.test.ts
  i18n/en.json
Labels: type: enhancement, topic: code, type: imperfection

#1866 fix: library search boosting
  arduino-ide-extension/package.json
  arduino-ide-extension/src/browser/boards/boards-list-widget.ts
  arduino-ide-extension/src/browser/library/library-list-widget.ts
  arduino-ide-extension/src/browser/widgets/component-list/component-list.tsx
  arduino-ide-extension/src/browser/widgets/component-list/filterable-list-container.tsx
  arduino-ide-extension/src/browser/widgets/component-list/list-widget.tsx
  arduino-ide-extension/src/common/protocol/arduino-component.ts
  arduino-ide-extension/src/common/protocol/searchable.ts
  arduino-ide-extension/src/node/boards-service-impl.ts
  arduino-ide-extension/src/node/library-service-impl.ts
  arduino-ide-extension/src/test/node/boards-service-impl.slow-test.ts
  arduino-ide-extension/src/test/node/core-service-impl.slow-test.ts
  arduino-ide-extension/src/test/node/library-service-impl.slow-test.ts
  arduino-ide-extension/src/test/node/test-bindings.ts
Labels: topic: code, type: imperfection

#1881 feat: moved login entry point to the side-bar
  arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/auth/authentication-client-service.ts
  arduino-ide-extension/src/browser/auth/cloud-user-commands.ts
  arduino-ide-extension/src/browser/contributions/account.ts
  arduino-ide-extension/src/browser/menu/arduino-menus.ts
  arduino-ide-extension/src/browser/style/cloud-sketchbook.css
  arduino-ide-extension/src/browser/theia/core/sidebar-bottom-menu-widget.tsx
  arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-composite-widget.tsx
  arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-contributions.ts
  arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-tree-widget.tsx
  arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-user-status.tsx
  i18n/en.json
Labels: type: enhancement, topic: code

#1904 Bump go version in workflow .yml files
  .github/workflows/build.yml
  .github/workflows/check-i18n-task.yml
  .github/workflows/i18n-nightly-push.yml
  .github/workflows/i18n-weekly-pull.yml
  .github/workflows/themes-weekly-pull.yml
Labels: type: enhancement, topic: infrastructure

#1909 chore: Updated to `0.31.0-rc.1` CLI
  arduino-ide-extension/package.json
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/board_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/board_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_grpc_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_grpc_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/common_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/common_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/compile_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/compile_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/port_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/port_pb.js
  arduino-ide-extension/src/node/sketches-service-impl.ts
Labels: type: enhancement, topic: code

#1916 build: can force notarization on macOS if not on a CI
  electron/build/scripts/notarize.js
Labels: topic: code

#1919 Use Apple Silicon build artifact name required by electron-updater
  electron/packager/config.js
Labels: topic: infrastructure, architecture: arm, os: macos, type: imperfection

#1913 Enhance board config auto-selection with hardwareId
  arduino-ide-extension/src/browser/boards/boards-service-provider.ts
  arduino-ide-extension/src/common/protocol/boards-service.ts
  arduino-ide-extension/src/node/board-discovery.ts
Labels: type: enhancement, topic: code

#1921 Bump CLI to 0.31.0
  arduino-ide-extension/package.json
Labels: type: enhancement, topic: infrastructure, topic: CLI
