Repository arduino/arduino-ide, pull requests merged in 2023-04, with the labels that each got.

#2013 feat(infra): support for `topic: cloud` label
  .github/label-configuration-files/labels.yml
Labels: type: enhancement, topic: infrastructure

#1983 ci: use `ubuntu-20.04` for the Linux build
  .github/workflows/build.yml
Labels: type: enhancement, topic: infrastructure, os: linux

#1965 fix: propagate monitor errors to the frontend
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/monitor-manager-proxy-client-impl.ts
  arduino-ide-extension/src/browser/monitor-model.ts
  arduino-ide-extension/src/browser/serial/monitor/monitor-view-contribution.tsx
  arduino-ide-extension/src/browser/serial/monitor/monitor-widget.tsx
  arduino-ide-extension/src/browser/serial/monitor/serial-monitor-send-input.tsx
  arduino-ide-extension/src/browser/style/index.css
  arduino-ide-extension/src/browser/style/monitor.css
  arduino-ide-extension/src/common/protocol/core-service.ts
  arduino-ide-extension/src/common/protocol/monitor-service.ts
  arduino-ide-extension/src/node/core-service-impl.ts
  arduino-ide-extension/src/node/monitor-manager-proxy-impl.ts
  arduino-ide-extension/src/node/monitor-manager.ts
  arduino-ide-extension/src/node/monitor-service.ts
  arduino-ide-extension/src/node/monitor-settings/monitor-settings-provider.ts
  i18n/en.json
Labels: topic: code, type: imperfection, topic: serial monitor

#1996 chore: Updated to `0.32.2` CLI
  arduino-ide-extension/package.json
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/compile_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/compile_pb.js
Labels: topic: CLI

#1986 fix: updated to `electron-builder@23.6.0`
  .github/workflows/build.yml
  electron/build/template-package.json
Labels: os: windows, type: imperfection

#1988 fix: update `themeId` settings after theme change
  arduino-ide-extension/src/browser/dialogs/settings/settings.ts
Labels: topic: code, type: imperfection, topic: theme

#2010 fix: try fetch the sketch by path if not in the cache
  arduino-ide-extension/src/browser/create/create-api.ts
  arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketch-cache.ts
  arduino-ide-extension/src/test/browser/create-api.test.ts
Labels: topic: code, type: imperfection, topic: cloud

#2019 chore: Prepared for the `2.1.0` release
  arduino-ide-extension/package.json
  electron-app/package.json
  package.json
Labels: topic: code

#2020 Don't upload "channel update info files" related to manual builds to S3 on release
  .github/workflows/build.yml
Labels: type: enhancement, topic: infrastructure

#2025 chore: Updated to the next version after release.
  arduino-ide-extension/package.json
  electron-app/package.json
  package.json
Labels: topic: code

#2024 Document 3rd party theme installation in "Advanced Usage"
  docs/advanced-usage.md
Labels: topic: documentation, type: enhancement, topic: theme

#2026 Corrected library.properties assignment w.r.t description and summary
  arduino-ide-extension/src/node/library-service-impl.ts
Labels: topic: code, type: imperfection

#2014 fix: reduced unnecessary `GET /sketches` request
  arduino-ide-extension/src/browser/create/create-api.ts
  arduino-ide-extension/src/test/browser/create-api.test.ts
Labels: topic: code, type: imperfection, topic: cloud
