Repository arduino/arduino-ide, pull requests merged in 2023-08, with the labels that each got.

#2174 fix: handle `UNKNOWN` code on `syscall: 'stat'`
  arduino-ide-extension/src/node/sketches-service-impl.ts
  arduino-ide-extension/src/node/utils/errors.ts
  arduino-ide-extension/src/test/node/sketches-service-impl.slow-test.ts
Labels: topic: code, os: windows, type: imperfection

#2181 fix: incorrect certificate flashing command string
  arduino-ide-extension/src/browser/contributions/upload-certificate.ts
  arduino-ide-extension/src/common/protocol/arduino-firmware-uploader.ts
  arduino-ide-extension/src/node/arduino-firmware-uploader-impl.ts
Labels: topic: code, type: imperfection

#2182 fix: execute the Arduino CLI without a `shell`
  arduino-ide-extension/src/node/arduino-daemon-impl.ts
  arduino-ide-extension/src/node/daemon-watcher.ts
Labels: type: enhancement, topic: code, topic: security, type: imperfection

#2177 Do full run of "Arduino IDE" workflow on tag push
  .github/workflows/build.yml
Labels: topic: infrastructure, type: imperfection

#2183 fix: falsy context menu `handlerId`
  arduino-ide-extension/src/electron-main/arduino-electron-main-module.ts
  arduino-ide-extension/src/electron-main/theia/theia-api-main.ts
Labels: topic: code, type: imperfection, topic: theia

#2191 chore: bump the version to `2.2.0`
  arduino-ide-extension/package.json
  electron-app/package.json
  package.json
Labels: type: enhancement, topic: infrastructure

#2195 fix: name of translation (`UA`) module
  arduino-ide-extension/src/node/i18n/arduino-localization-contribution.ts
Labels: topic: code, type: imperfection

#2197 chore: update version to `2.2.1`
  arduino-ide-extension/package.json
  electron-app/package.json
  package.json
Labels: topic: infrastructure

#2202 fix(i18n): corrected the module for `tr` and `ru`
  arduino-ide-extension/src/node/i18n/arduino-localization-contribution.ts
Labels: topic: code, type: imperfection

#2204 fix(ci): fix the changelog generation
  .github/workflows/compose-full-changelog.yml
Labels: topic: infrastructure, type: imperfection

#2206 chore: update to `arduino-fwuploader@2.4.1`
  arduino-ide-extension/package.json
Labels: type: imperfection, topic: CLI
