Repository arduino/arduino-ide, pull requests merged in 2023-03, with the labels that each got.

#1922 fix: no unnecessary tree update on mouse over/out
  arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-tree-widget.tsx
Labels: topic: code, type: imperfection

#1910 fix: encoding when reading a cloud sketch
  arduino-ide-extension/src/browser/create/create-api.ts
  arduino-ide-extension/src/browser/create/create-fs-provider.ts
  arduino-ide-extension/src/common/utils.ts
Labels: topic: code, type: imperfection

#1928 fix: scroll to the bottom after the state update
  arduino-ide-extension/src/browser/serial/monitor/monitor-widget.tsx
  arduino-ide-extension/src/browser/serial/monitor/serial-monitor-send-output.tsx
Labels: topic: code, type: imperfection, topic: serial monitor

#1948 fix: jsonc parsing in the IDE2 backend
  arduino-ide-extension/package.json
  arduino-ide-extension/src/node/arduino-daemon-impl.ts
  arduino-ide-extension/src/node/arduino-ide-backend-module.ts
  arduino-ide-extension/src/node/settings-reader.ts
  arduino-ide-extension/src/node/sketches-service-impl.ts
  arduino-ide-extension/src/test/node/settings.reader.test.ts
  arduino-ide-extension/src/test/node/test-bindings.ts
Labels: topic: code, type: imperfection

#1954 Add bundled tools version check step to release procedure
  docs/internal/release-procedure.md
Labels: topic: documentation, type: enhancement

#1947 fix: use text `--format` for the CLI
  arduino-ide-extension/package.json
  arduino-ide-extension/src/node/arduino-daemon-impl.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_grpc_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/commands_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/core_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/core_pb.js
Labels: topic: code, type: imperfection, topic: CLI

#1927 feat: new UX for the boards/library manager widget
  arduino-ide-extension/package.json
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/boards/boards-auto-installer.ts
  arduino-ide-extension/src/browser/contributions/examples.ts
  arduino-ide-extension/src/browser/library/library-list-widget.ts
  arduino-ide-extension/src/browser/menu/arduino-menus.ts
  arduino-ide-extension/src/browser/style/boards-config-dialog.css
  arduino-ide-extension/src/browser/style/dialogs.css
  arduino-ide-extension/src/browser/style/fonts.css
  arduino-ide-extension/src/browser/style/ide-updater-dialog.css
  arduino-ide-extension/src/browser/style/index.css
  arduino-ide-extension/src/browser/style/list-widget.css
  arduino-ide-extension/src/browser/style/main.css
  arduino-ide-extension/src/browser/widgets/component-list/component-list-item.tsx
  arduino-ide-extension/src/browser/widgets/component-list/component-list.tsx
  arduino-ide-extension/src/browser/widgets/component-list/filterable-list-container.tsx
  arduino-ide-extension/src/browser/widgets/component-list/list-item-renderer.tsx
  arduino-ide-extension/src/browser/widgets/component-list/list-widget.tsx
  arduino-ide-extension/src/common/protocol/arduino-component.ts
  arduino-ide-extension/src/common/protocol/examples-service.ts
  arduino-ide-extension/src/common/protocol/installable.ts
  arduino-ide-extension/src/common/protocol/library-service.ts
  arduino-ide-extension/src/node/examples-service-impl.ts
  arduino-ide-extension/src/node/library-service-impl.ts
  arduino-ide-extension/src/test/browser/fixtures/boards.ts
  arduino-ide-extension/src/test/common/installable.test.ts
  i18n/en.json
  package.json
  yarn.lock
Labels: type: enhancement, topic: code, type: imperfection

#1901 feat: introduced cloud states
  arduino-ide-extension/arduino-icons.json
  arduino-ide-extension/package.json
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/contributions/account.ts
  arduino-ide-extension/src/browser/contributions/cloud-contribution.ts
  arduino-ide-extension/src/browser/contributions/contribution.ts
  arduino-ide-extension/src/browser/contributions/create-cloud-copy.ts
  arduino-ide-extension/src/browser/contributions/new-cloud-sketch.ts
  arduino-ide-extension/src/browser/contributions/rename-cloud-sketch.ts
  arduino-ide-extension/src/browser/contributions/save-as-sketch.ts
  arduino-ide-extension/src/browser/create/create-api.ts
  arduino-ide-extension/src/browser/create/create-features.ts
  arduino-ide-extension/src/browser/icons/arduino-cloud-download.svg
  arduino-ide-extension/src/browser/icons/arduino-cloud-filled-offline.svg
  arduino-ide-extension/src/browser/icons/arduino-cloud-filled.svg
  arduino-ide-extension/src/browser/icons/arduino-cloud-offline.svg
  arduino-ide-extension/src/browser/icons/arduino-cloud-upload.svg
  arduino-ide-extension/src/browser/icons/arduino-cloud.svg
  arduino-ide-extension/src/browser/style/account-icon.svg
  arduino-ide-extension/src/browser/style/cloud-sketchbook.css
  arduino-ide-extension/src/browser/style/fonts.css
  arduino-ide-extension/src/browser/style/fonts/FontAwesome.svg
  arduino-ide-extension/src/browser/style/fonts/FontAwesome.ttf
  arduino-ide-extension/src/browser/style/fonts/FontAwesome.woff
  arduino-ide-extension/src/browser/style/main.css
  arduino-ide-extension/src/browser/style/sketch-folder-icon.svg
  arduino-ide-extension/src/browser/style/sketchbook.css
  arduino-ide-extension/src/browser/theia/core/connection-status-service.ts
  arduino-ide-extension/src/browser/theia/core/sidebar-bottom-menu-widget.tsx
  arduino-ide-extension/src/browser/theia/core/window-title-updater.ts
  arduino-ide-extension/src/browser/theia/messages/notifications-manager.ts
  arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-commands.ts
  arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-composite-widget.tsx
  arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-contributions.ts
  arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-tree-model.ts
  arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-tree-widget.tsx
  arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-tree.ts
  arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-status.tsx
  arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-commands.ts
  arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-tree-widget.tsx
  arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-tree.ts
  arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-widget-contribution.ts
  arduino-ide-extension/src/common/protocol/sketches-service.ts
  arduino-ide-extension/src/common/utils.ts
  arduino-ide-extension/src/node/sketches-service-impl.ts
  arduino-ide-extension/src/test/browser/connection-status-service.test.ts
  arduino-ide-extension/src/test/node/boards-service-impl.slow-test.ts
  arduino-ide-extension/src/test/node/core-service-impl.slow-test.ts
  arduino-ide-extension/src/test/node/library-service-impl.slow-test.ts
  arduino-ide-extension/src/test/node/sketches-service-impl.slow-test.ts
  arduino-ide-extension/src/test/node/test-bindings.ts
  i18n/en.json
  yarn.lock
Labels: type: enhancement, topic: code

#1949 feat: omit release details to speed up lib search
  arduino-ide-extension/package.json
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/lib_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/lib_pb.js
  arduino-ide-extension/src/node/library-service-impl.ts
Labels: type: enhancement, topic: code

#1972 fix: let the resource finish all write operation
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/theia/filesystem/file-resource.ts
Labels: topic: code, type: imperfection, topic: theia

#1969 fix: incorrect editor widget key calculation
  arduino-ide-extension/src/browser/contributions/open-sketch-files.ts
Labels: topic: code, type: imperfection

#1979 feat: re-focus monitor widget after verify/upload
  arduino-ide-extension/src/browser/contributions/contribution.ts
Labels: type: enhancement, topic: code, topic: serial monitor

#1978 fix: the focus in the sketchbook widget
  arduino-ide-extension/src/browser/library/library-list-widget.ts
  arduino-ide-extension/src/browser/utils/dom.ts
  arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-composite-widget.tsx
  arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-widget.tsx
Labels: topic: code, type: imperfection
