Repository arduino/arduino-ide, pull requests merged in 2023-06, with the labels that each got.

#2067 fix: removed unsafe `shell` when executing process
  arduino-ide-extension/package.json
  arduino-ide-extension/src/common/protocol/executable-service.ts
  arduino-ide-extension/src/node/arduino-daemon-impl.ts
  arduino-ide-extension/src/node/arduino-firmware-uploader-impl.ts
  arduino-ide-extension/src/node/clang-formatter.ts
  arduino-ide-extension/src/node/config-service-impl.ts
  arduino-ide-extension/src/node/exec-util.ts
  arduino-ide-extension/src/node/executable-service-impl.ts
  arduino-ide-extension/src/test/node/arduino-daemon-impl.test.ts
  arduino-ide-extension/src/test/node/clang-formatter.test.ts
  arduino-ide-extension/src/test/node/exec-util.test.ts
  yarn.lock
Labels: topic: code, topic: security, type: imperfection

#2083 chore(cli): Bumped the CLI version to `0.33.0`
  arduino-ide-extension/package.json
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/board_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/board_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/common_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/common_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/compile_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/compile_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/core_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/core_pb.js
Labels: topic: infrastructure, topic: CLI

#2090 fix: omit port from upload request when not set
  arduino-ide-extension/src/node/core-service-impl.ts
  arduino-ide-extension/src/test/node/core-service-impl.test.ts
Labels: topic: code, type: imperfection

#2080 fix: relaxed `saveAll` if no Internet connection
  arduino-ide-extension/src/browser/theia/core/application-shell.ts
Labels: topic: code, type: imperfection

#2082 fix: warn user when IDE cannot save the sketch
  arduino-ide-extension/src/browser/contributions/contribution.ts
  arduino-ide-extension/src/browser/contributions/save-as-sketch.ts
  arduino-ide-extension/src/browser/contributions/save-sketch.ts
  arduino-ide-extension/src/browser/theia/core/connection-status-service.ts
  arduino-ide-extension/src/test/browser/connection-status-service.test.ts
Labels: topic: code, type: imperfection

#2078 add linux-arm64 to download-ls
  arduino-ide-extension/scripts/download-ls.js
Labels: type: enhancement, topic: infrastructure, architecture: arm, os: linux, topic: language server

#2119 Revert "chore(cli): Bumped the CLI version to `0.33.0`"
  arduino-ide-extension/package.json
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/board_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/board_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/common_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/common_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/compile_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/compile_pb.js
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/core_pb.d.ts
  arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/core_pb.js
Labels: topic: CLI

#2121 chore(cli): Bumped the CLI version to `0.32.3`
  arduino-ide-extension/package.json
Labels: topic: CLI

#2120 Adjust release procedure and CI system for "trunk-based" development strategy
  .github/workflows/build.yml
  .github/workflows/check-certificates.yml
  .github/workflows/check-i18n-task.yml
  docs/internal/release-procedure.md
Labels: topic: documentation, type: enhancement, topic: infrastructure
