Repository arduino/arduino-ide, pull requests merged in 2024-11, with the labels that each got.

#2554 fix: disable local windows signing for external contributions
  .github/workflows/build.yml
  electron-app/scripts/windowsCustomSign.js
Labels: topic: infrastructure, os: windows

#2563 Add `PAID_RUNNER_BUILD_DATA` environment variable back to build workflow
  .github/workflows/build.yml
Labels: type: enhancement, topic: infrastructure

#2564 Simplify and generalize configurable working directory code in build workflow
  .github/workflows/build.yml
Labels: type: enhancement, topic: infrastructure

#2565 Use appropriate indicator for dependency installation conditionals in build workflow
  .github/workflows/build.yml
Labels: topic: infrastructure, os: windows, type: imperfection

#2566 Get job-specific configuration from matrix in build workflow
  .github/workflows/build.yml
Labels: topic: infrastructure, os: windows, type: imperfection

#2567 Remove inaccurate and redundant signing determination code from build system
  .github/workflows/build.yml
  electron-app/scripts/windowsCustomSign.js
Labels: topic: infrastructure, os: windows, type: imperfection

#2555 fix: memory leak when scanning sketchbooks with large files
  arduino-ide-extension/package.json
  arduino-ide-extension/scripts/generate-protocol.js
  arduino-ide-extension/src/node/sketches-service-impl.ts
  electron-app/scripts/post-package.js
  yarn.lock
Labels: topic: code, type: imperfection

#2553 feat: implement menu action to reload current board data
  arduino-ide-extension/src/browser/boards/boards-data-store.ts
  arduino-ide-extension/src/browser/contributions/board-selection.ts
  arduino-ide-extension/src/common/protocol/boards-service.ts
  arduino-ide-extension/src/node/boards-service-impl.ts
  i18n/en.json
Labels: type: enhancement, topic: code

#2574 fix: update `yarn.lock`
  yarn.lock
Labels: topic: infrastructure, type: imperfection

#2397 feat: can skip verify before upload
  arduino-ide-extension/src/browser/arduino-preferences.ts
  arduino-ide-extension/src/browser/contributions/upload-sketch.ts
  arduino-ide-extension/src/browser/contributions/verify-sketch.ts
  i18n/en.json
Labels: type: enhancement, topic: code
