Repository arduino/arduino-ide, pull requests merged in 2024-01, with the labels that each got.

#2288 fix: can open IDE2 from an ino file
  arduino-ide-extension/src/electron-main/theia/electron-main-application.ts
Labels: topic: code, type: imperfection

#2291 fix: board `<select>` update on board detach
  arduino-ide-extension/src/browser/dialogs/certificate-uploader/certificate-uploader-component.tsx
  arduino-ide-extension/src/browser/dialogs/certificate-uploader/select-board-components.tsx
  arduino-ide-extension/src/browser/dialogs/firmware-uploader/firmware-uploader-component.tsx
Labels: topic: code, type: imperfection

#2322 Bump built-in example sketches version to 1.10.1
  arduino-ide-extension/scripts/download-examples.js
Labels: type: enhancement, topic: infrastructure

#2338 Bundle native Arduino Firmware Uploader with Apple Silicon build
  arduino-ide-extension/scripts/download-fwuploader.js
Labels: type: enhancement, topic: infrastructure, architecture: arm, os: macos

#2342 feat: disable debug widget if unsupported by board
  arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
  arduino-ide-extension/src/browser/contributions/debug.ts
  arduino-ide-extension/src/browser/style/debug.css
  arduino-ide-extension/src/browser/theia/debug/debug-configuration-widget.tsx
  arduino-ide-extension/src/browser/theia/debug/debug-widget.ts
Labels: type: enhancement, topic: code, topic: debugger
