Repository arduino/arduino-ide, pull requests merged in 2025-04, with the labels that each got.

#2672 Give build workflow step access to required deployment environment
  .github/workflows/build.yml
Labels: topic: infrastructure, type: imperfection

#2675 fix: add missing linux dependencies for `merge-channel-files` job
  .github/workflows/build.yml
Labels: topic: infrastructure, os: linux, type: imperfection

#2677 fix: add missing linux dependencies for `create-changelog` job
  .github/workflows/compose-full-changelog.yml
Labels: topic: infrastructure, os: linux

#2681 fix: prevent `OutputWidget` to gain focus when updated
  arduino-ide-extension/src/browser/theia/core/application-shell.ts
Labels: topic: code, topic: theia

#2686 fix: propagate electron params in second instance startup
  arduino-ide-extension/src/electron-main/theia/electron-main-application.ts
Labels: topic: code, type: imperfection

#2693 fix: wait for theia `initalWindow` to be set before opening sketch through `open-file` event
  arduino-ide-extension/src/common/utils.ts
  arduino-ide-extension/src/electron-main/theia/electron-main-application.ts
  electron-app/package.json
Labels: topic: code, type: imperfection

#2697 fix: use `ElectronConnectionHandler` to connect the ide updater frontend and the electron main process
  arduino-ide-extension/src/electron-main/arduino-electron-main-module.ts
Labels: type: imperfection, topic: theia
